// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/attributes/attributes.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.attributes;

public interface CreateAttributeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.attributes.CreateAttributeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required
   * </pre>
   *
   * <code>string namespace_id = 1 [json_name = "namespaceId", (.buf.validate.field) = { ... }</code>
   * @return The namespaceId.
   */
  java.lang.String getNamespaceId();
  /**
   * <pre>
   * Required
   * </pre>
   *
   * <code>string namespace_id = 1 [json_name = "namespaceId", (.buf.validate.field) = { ... }</code>
   * @return The bytes for namespaceId.
   */
  com.google.protobuf.ByteString
      getNamespaceIdBytes();

  /**
   * <code>string name = 2 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.policy.AttributeRuleTypeEnum rule = 3 [json_name = "rule", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for rule.
   */
  int getRuleValue();
  /**
   * <code>.policy.AttributeRuleTypeEnum rule = 3 [json_name = "rule", (.buf.validate.field) = { ... }</code>
   * @return The rule.
   */
  io.opentdf.platform.policy.AttributeRuleTypeEnum getRule();

  /**
   * <pre>
   * Optional attribute values (when provided) must be alphanumeric strings, allowing hyphens and underscores but not as the first or last character.
   * The stored attribute value will be normalized to lower case.
   * </pre>
   *
   * <code>repeated string values = 4 [json_name = "values", (.buf.validate.field) = { ... }</code>
   * @return A list containing the values.
   */
  java.util.List<java.lang.String>
      getValuesList();
  /**
   * <pre>
   * Optional attribute values (when provided) must be alphanumeric strings, allowing hyphens and underscores but not as the first or last character.
   * The stored attribute value will be normalized to lower case.
   * </pre>
   *
   * <code>repeated string values = 4 [json_name = "values", (.buf.validate.field) = { ... }</code>
   * @return The count of values.
   */
  int getValuesCount();
  /**
   * <pre>
   * Optional attribute values (when provided) must be alphanumeric strings, allowing hyphens and underscores but not as the first or last character.
   * The stored attribute value will be normalized to lower case.
   * </pre>
   *
   * <code>repeated string values = 4 [json_name = "values", (.buf.validate.field) = { ... }</code>
   * @param index The index of the element to return.
   * @return The values at the given index.
   */
  java.lang.String getValues(int index);
  /**
   * <pre>
   * Optional attribute values (when provided) must be alphanumeric strings, allowing hyphens and underscores but not as the first or last character.
   * The stored attribute value will be normalized to lower case.
   * </pre>
   *
   * <code>repeated string values = 4 [json_name = "values", (.buf.validate.field) = { ... }</code>
   * @param index The index of the value to return.
   * @return The bytes of the values at the given index.
   */
  com.google.protobuf.ByteString
      getValuesBytes(int index);

  /**
   * <pre>
   * Optional
   * </pre>
   *
   * <code>.common.MetadataMutable metadata = 100 [json_name = "metadata"];</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * Optional
   * </pre>
   *
   * <code>.common.MetadataMutable metadata = 100 [json_name = "metadata"];</code>
   * @return The metadata.
   */
  io.opentdf.platform.common.MetadataMutable getMetadata();
  /**
   * <pre>
   * Optional
   * </pre>
   *
   * <code>.common.MetadataMutable metadata = 100 [json_name = "metadata"];</code>
   */
  io.opentdf.platform.common.MetadataMutableOrBuilder getMetadataOrBuilder();
}
