// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/unsafe/unsafe.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.unsafe;

public interface UnsafeUpdateNamespaceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.unsafe.UnsafeUpdateNamespaceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Required
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
