// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/unsafe/unsafe.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.unsafe;

public interface UnsafeUpdateAttributeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.unsafe.UnsafeUpdateAttributeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Required
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Optional
   * WARNING!! 
   * Updating the name of an Attribute will retroactively alter access to existing TDFs of the old and new Attribute name.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Optional
   * WARNING!! 
   * Updating the name of an Attribute will retroactively alter access to existing TDFs of the old and new Attribute name.
   * </pre>
   *
   * <code>string name = 2 [json_name = "name", (.buf.validate.field) = { ... }</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * WARNING!! 
   * Updating the rule of an Attribute will retroactively alter access to existing TDFs of the Attribute name.
   * </pre>
   *
   * <code>.policy.AttributeRuleTypeEnum rule = 3 [json_name = "rule", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for rule.
   */
  int getRuleValue();
  /**
   * <pre>
   * WARNING!! 
   * Updating the rule of an Attribute will retroactively alter access to existing TDFs of the Attribute name.
   * </pre>
   *
   * <code>.policy.AttributeRuleTypeEnum rule = 3 [json_name = "rule", (.buf.validate.field) = { ... }</code>
   * @return The rule.
   */
  io.opentdf.platform.policy.AttributeRuleTypeEnum getRule();

  /**
   * <pre>
   * WARNING!!
   * Unsafe reordering requires the full list of values in the new order they should be stored. Updating the order of values in a HIERARCHY-rule Attribute Definition
   * will retroactively alter access to existing TDFs containing those values. Replacing values on an attribute in place is not supported; values can be unsafely deleted
   * deleted, created, and unsafely re-ordered as necessary.
   * </pre>
   *
   * <code>repeated string values_order = 4 [json_name = "valuesOrder"];</code>
   * @return A list containing the valuesOrder.
   */
  java.util.List<java.lang.String>
      getValuesOrderList();
  /**
   * <pre>
   * WARNING!!
   * Unsafe reordering requires the full list of values in the new order they should be stored. Updating the order of values in a HIERARCHY-rule Attribute Definition
   * will retroactively alter access to existing TDFs containing those values. Replacing values on an attribute in place is not supported; values can be unsafely deleted
   * deleted, created, and unsafely re-ordered as necessary.
   * </pre>
   *
   * <code>repeated string values_order = 4 [json_name = "valuesOrder"];</code>
   * @return The count of valuesOrder.
   */
  int getValuesOrderCount();
  /**
   * <pre>
   * WARNING!!
   * Unsafe reordering requires the full list of values in the new order they should be stored. Updating the order of values in a HIERARCHY-rule Attribute Definition
   * will retroactively alter access to existing TDFs containing those values. Replacing values on an attribute in place is not supported; values can be unsafely deleted
   * deleted, created, and unsafely re-ordered as necessary.
   * </pre>
   *
   * <code>repeated string values_order = 4 [json_name = "valuesOrder"];</code>
   * @param index The index of the element to return.
   * @return The valuesOrder at the given index.
   */
  java.lang.String getValuesOrder(int index);
  /**
   * <pre>
   * WARNING!!
   * Unsafe reordering requires the full list of values in the new order they should be stored. Updating the order of values in a HIERARCHY-rule Attribute Definition
   * will retroactively alter access to existing TDFs containing those values. Replacing values on an attribute in place is not supported; values can be unsafely deleted
   * deleted, created, and unsafely re-ordered as necessary.
   * </pre>
   *
   * <code>repeated string values_order = 4 [json_name = "valuesOrder"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the valuesOrder at the given index.
   */
  com.google.protobuf.ByteString
      getValuesOrderBytes(int index);
}
