// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/unsafe/unsafe.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.unsafe;

public interface UnsafeUpdateAttributeValueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.unsafe.UnsafeUpdateAttributeValueRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string value = 2 [json_name = "value", (.buf.validate.field) = { ... }</code>
   * @return The value.
   */
  java.lang.String getValue();
  /**
   * <code>string value = 2 [json_name = "value", (.buf.validate.field) = { ... }</code>
   * @return The bytes for value.
   */
  com.google.protobuf.ByteString
      getValueBytes();
}
