// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/unsafe/unsafe.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.unsafe;

public interface UnsafeDeleteNamespaceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.unsafe.UnsafeDeleteNamespaceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.policy.Namespace namespace = 1 [json_name = "namespace"];</code>
   * @return Whether the namespace field is set.
   */
  boolean hasNamespace();
  /**
   * <code>.policy.Namespace namespace = 1 [json_name = "namespace"];</code>
   * @return The namespace.
   */
  io.opentdf.platform.policy.Namespace getNamespace();
  /**
   * <code>.policy.Namespace namespace = 1 [json_name = "namespace"];</code>
   */
  io.opentdf.platform.policy.NamespaceOrBuilder getNamespaceOrBuilder();
}
