// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/unsafe/unsafe.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.unsafe;

public final class UnsafeProto {
  private UnsafeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeUpdateNamespaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeUpdateNamespaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeUpdateNamespaceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeUpdateNamespaceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeReactivateNamespaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeReactivateNamespaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeReactivateNamespaceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeReactivateNamespaceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeDeleteNamespaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeDeleteNamespaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeDeleteNamespaceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeDeleteNamespaceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeUpdateAttributeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeUpdateAttributeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeUpdateAttributeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeUpdateAttributeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeReactivateAttributeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeReactivateAttributeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeReactivateAttributeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeReactivateAttributeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeDeleteAttributeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeDeleteAttributeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeDeleteAttributeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeDeleteAttributeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeUpdateAttributeValueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeUpdateAttributeValueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeUpdateAttributeValueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeUpdateAttributeValueResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeReactivateAttributeValueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeReactivateAttributeValueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeReactivateAttributeValueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeReactivateAttributeValueResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeDeleteAttributeValueRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeDeleteAttributeValueRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_unsafe_UnsafeDeleteAttributeValueResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_unsafe_UnsafeDeleteAttributeValueResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032policy/unsafe/unsafe.proto\022\rpolicy.uns" +
      "afe\032\033buf/validate/validate.proto\032\034google" +
      "/api/annotations.proto\032\024policy/objects.p" +
      "roto\"\351\004\n\034UnsafeUpdateNamespaceRequest\022\026\n" +
      "\002id\030\001 \001(\tB\006\272H\003\310\001\001R\002id\022\260\004\n\004name\030\002 \001(\tB\233\004\272" +
      "H\227\004r\003\030\375\001\272\001\216\004\n\025namespace_name_format\022\241\003Na" +
      "mespace must be a valid hostname. It sho" +
      "uld include at least one dot, with each " +
      "segment (label) starting and ending with" +
      " an alphanumeric character. Each label m" +
      "ust be 1 to 63 characters long, allowing" +
      " hyphens but not as the first or last ch" +
      "aracter. The top-level domain (the last " +
      "segment after the final dot) must consis" +
      "t of at least two alphabetic characters." +
      " The stored namespace will be normalized" +
      " to lower case.\032Qthis.matches(\'^([a-zA-Z" +
      "0-9]([a-zA-Z0-9\\\\-]{0,61}[a-zA-Z0-9])?\\\\" +
      ".)+[a-zA-Z]{2,}$\')R\004name\"P\n\035UnsafeUpdate" +
      "NamespaceResponse\022/\n\tnamespace\030\001 \001(\0132\021.p" +
      "olicy.NamespaceR\tnamespace\":\n UnsafeReac" +
      "tivateNamespaceRequest\022\026\n\002id\030\001 \001(\tB\006\272H\003\310" +
      "\001\001R\002id\"T\n!UnsafeReactivateNamespaceRespo" +
      "nse\022/\n\tnamespace\030\001 \001(\0132\021.policy.Namespac" +
      "eR\tnamespace\"P\n\034UnsafeDeleteNamespaceReq" +
      "uest\022\026\n\002id\030\001 \001(\tB\006\272H\003\310\001\001R\002id\022\030\n\003fqn\030\002 \001(" +
      "\tB\006\272H\003\310\001\001R\003fqn\"P\n\035UnsafeDeleteNamespaceR" +
      "esponse\022/\n\tnamespace\030\001 \001(\0132\021.policy.Name" +
      "spaceR\tnamespace\"\335\003\n\034UnsafeUpdateAttribu" +
      "teRequest\022\026\n\002id\030\001 \001(\tB\006\272H\003\310\001\001R\002id\022\304\002\n\004na" +
      "me\030\002 \001(\tB\257\002\272H\253\002r\003\030\375\001\272\001\242\002\n\025attribute_name" +
      "_format\022\263\001Attribute name must be an alph" +
      "anumeric string, allowing hyphens and un" +
      "derscores but not as the first or last c" +
      "haracter. The stored attribute name will" +
      " be normalized to lower case.\032Ssize(this" +
      ") > 0 ? this.matches(\'^[a-zA-Z0-9](?:[a-" +
      "zA-Z0-9_-]*[a-zA-Z0-9])?$\') : trueR\004name" +
      "\022;\n\004rule\030\003 \001(\0162\035.policy.AttributeRuleTyp" +
      "eEnumB\010\272H\005\202\001\002\020\001R\004rule\022!\n\014values_order\030\004 " +
      "\003(\tR\013valuesOrder\"P\n\035UnsafeUpdateAttribut" +
      "eResponse\022/\n\tattribute\030\001 \001(\0132\021.policy.At" +
      "tributeR\tattribute\":\n UnsafeReactivateAt" +
      "tributeRequest\022\026\n\002id\030\001 \001(\tB\006\272H\003\310\001\001R\002id\"T" +
      "\n!UnsafeReactivateAttributeResponse\022/\n\ta" +
      "ttribute\030\001 \001(\0132\021.policy.AttributeR\tattri" +
      "bute\"P\n\034UnsafeDeleteAttributeRequest\022\026\n\002" +
      "id\030\001 \001(\tB\006\272H\003\310\001\001R\002id\022\030\n\003fqn\030\002 \001(\tB\006\272H\003\310\001" +
      "\001R\003fqn\"P\n\035UnsafeDeleteAttributeResponse\022" +
      "/\n\tattribute\030\001 \001(\0132\021.policy.AttributeR\ta" +
      "ttribute\"\345\002\n!UnsafeUpdateAttributeValueR" +
      "equest\022\026\n\002id\030\001 \001(\tB\006\272H\003\310\001\001R\002id\022\247\002\n\005value" +
      "\030\002 \001(\tB\220\002\272H\214\002r\003\030\375\001\272\001\203\002\n\014value_format\022\265\001A" +
      "ttribute Value must be an alphanumeric s" +
      "tring, allowing hyphens and underscores " +
      "but not as the first or last character. " +
      "The stored attribute value will be norma" +
      "lized to lower case.\032;this.matches(\'^[a-" +
      "zA-Z0-9](?:[a-zA-Z0-9_-]*[a-zA-Z0-9])?$\'" +
      ")R\005value\"I\n\"UnsafeUpdateAttributeValueRe" +
      "sponse\022#\n\005value\030\001 \001(\0132\r.policy.ValueR\005va" +
      "lue\"?\n%UnsafeReactivateAttributeValueReq" +
      "uest\022\026\n\002id\030\001 \001(\tB\006\272H\003\310\001\001R\002id\"M\n&UnsafeRe" +
      "activateAttributeValueResponse\022#\n\005value\030" +
      "\001 \001(\0132\r.policy.ValueR\005value\"U\n!UnsafeDel" +
      "eteAttributeValueRequest\022\026\n\002id\030\001 \001(\tB\006\272H" +
      "\003\310\001\001R\002id\022\030\n\003fqn\030\002 \001(\tB\006\272H\003\310\001\001R\003fqn\"I\n\"Un" +
      "safeDeleteAttributeValueResponse\022#\n\005valu" +
      "e\030\001 \001(\0132\r.policy.ValueR\005value2\334\013\n\rUnsafe" +
      "Service\022\223\001\n\025UnsafeUpdateNamespace\022+.poli" +
      "cy.unsafe.UnsafeUpdateNamespaceRequest\032," +
      ".policy.unsafe.UnsafeUpdateNamespaceResp" +
      "onse\"\037\202\323\344\223\002\0312\027/unsafe/namespaces/{id}\022\252\001" +
      "\n\031UnsafeReactivateNamespace\022/.policy.uns" +
      "afe.UnsafeReactivateNamespaceRequest\0320.p" +
      "olicy.unsafe.UnsafeReactivateNamespaceRe" +
      "sponse\"*\202\323\344\223\002$\"\"/unsafe/namespaces/{id}/" +
      "reactivate\022\223\001\n\025UnsafeDeleteNamespace\022+.p" +
      "olicy.unsafe.UnsafeDeleteNamespaceReques" +
      "t\032,.policy.unsafe.UnsafeDeleteNamespaceR" +
      "esponse\"\037\202\323\344\223\002\031*\027/unsafe/namespaces/{id}" +
      "\022\223\001\n\025UnsafeUpdateAttribute\022+.policy.unsa" +
      "fe.UnsafeUpdateAttributeRequest\032,.policy" +
      ".unsafe.UnsafeUpdateAttributeResponse\"\037\202" +
      "\323\344\223\002\0312\027/unsafe/attributes/{id}\022\252\001\n\031Unsaf" +
      "eReactivateAttribute\022/.policy.unsafe.Uns" +
      "afeReactivateAttributeRequest\0320.policy.u" +
      "nsafe.UnsafeReactivateAttributeResponse\"" +
      "*\202\323\344\223\002$\"\"/unsafe/attributes/{id}/reactiv" +
      "ate\022\223\001\n\025UnsafeDeleteAttribute\022+.policy.u" +
      "nsafe.UnsafeDeleteAttributeRequest\032,.pol" +
      "icy.unsafe.UnsafeDeleteAttributeResponse" +
      "\"\037\202\323\344\223\002\031*\027/unsafe/attributes/{id}\022\251\001\n\032Un" +
      "safeUpdateAttributeValue\0220.policy.unsafe" +
      ".UnsafeUpdateAttributeValueRequest\0321.pol" +
      "icy.unsafe.UnsafeUpdateAttributeValueRes" +
      "ponse\"&\202\323\344\223\002 2\036/unsafe/attributes/values" +
      "/{id}\022\300\001\n\036UnsafeReactivateAttributeValue" +
      "\0224.policy.unsafe.UnsafeReactivateAttribu" +
      "teValueRequest\0325.policy.unsafe.UnsafeRea" +
      "ctivateAttributeValueResponse\"1\202\323\344\223\002+\")/" +
      "unsafe/attributes/values/{id}/reactivate" +
      "\022\251\001\n\032UnsafeDeleteAttributeValue\0220.policy" +
      ".unsafe.UnsafeDeleteAttributeValueReques" +
      "t\0321.policy.unsafe.UnsafeDeleteAttributeV" +
      "alueResponse\"&\202\323\344\223\002 *\036/unsafe/attributes" +
      "/values/{id}B\205\001\n!io.opentdf.platform.pol" +
      "icy.unsafeB\013UnsafeProtoP\001\242\002\003PUX\252\002\rPolicy" +
      ".Unsafe\312\002\rPolicy\\Unsafe\342\002\031Policy\\Unsafe\\" +
      "GPBMetadata\352\002\016Policy::Unsafeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          io.opentdf.platform.policy.ObjectsProto.getDescriptor(),
        });
    internal_static_policy_unsafe_UnsafeUpdateNamespaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_policy_unsafe_UnsafeUpdateNamespaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeUpdateNamespaceRequest_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_policy_unsafe_UnsafeUpdateNamespaceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_policy_unsafe_UnsafeUpdateNamespaceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeUpdateNamespaceResponse_descriptor,
        new java.lang.String[] { "Namespace", });
    internal_static_policy_unsafe_UnsafeReactivateNamespaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_policy_unsafe_UnsafeReactivateNamespaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeReactivateNamespaceRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_policy_unsafe_UnsafeReactivateNamespaceResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_policy_unsafe_UnsafeReactivateNamespaceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeReactivateNamespaceResponse_descriptor,
        new java.lang.String[] { "Namespace", });
    internal_static_policy_unsafe_UnsafeDeleteNamespaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_policy_unsafe_UnsafeDeleteNamespaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeDeleteNamespaceRequest_descriptor,
        new java.lang.String[] { "Id", "Fqn", });
    internal_static_policy_unsafe_UnsafeDeleteNamespaceResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_policy_unsafe_UnsafeDeleteNamespaceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeDeleteNamespaceResponse_descriptor,
        new java.lang.String[] { "Namespace", });
    internal_static_policy_unsafe_UnsafeUpdateAttributeRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_policy_unsafe_UnsafeUpdateAttributeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeUpdateAttributeRequest_descriptor,
        new java.lang.String[] { "Id", "Name", "Rule", "ValuesOrder", });
    internal_static_policy_unsafe_UnsafeUpdateAttributeResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_policy_unsafe_UnsafeUpdateAttributeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeUpdateAttributeResponse_descriptor,
        new java.lang.String[] { "Attribute", });
    internal_static_policy_unsafe_UnsafeReactivateAttributeRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_policy_unsafe_UnsafeReactivateAttributeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeReactivateAttributeRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_policy_unsafe_UnsafeReactivateAttributeResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_policy_unsafe_UnsafeReactivateAttributeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeReactivateAttributeResponse_descriptor,
        new java.lang.String[] { "Attribute", });
    internal_static_policy_unsafe_UnsafeDeleteAttributeRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_policy_unsafe_UnsafeDeleteAttributeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeDeleteAttributeRequest_descriptor,
        new java.lang.String[] { "Id", "Fqn", });
    internal_static_policy_unsafe_UnsafeDeleteAttributeResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_policy_unsafe_UnsafeDeleteAttributeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeDeleteAttributeResponse_descriptor,
        new java.lang.String[] { "Attribute", });
    internal_static_policy_unsafe_UnsafeUpdateAttributeValueRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_policy_unsafe_UnsafeUpdateAttributeValueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeUpdateAttributeValueRequest_descriptor,
        new java.lang.String[] { "Id", "Value", });
    internal_static_policy_unsafe_UnsafeUpdateAttributeValueResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_policy_unsafe_UnsafeUpdateAttributeValueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeUpdateAttributeValueResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_policy_unsafe_UnsafeReactivateAttributeValueRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_policy_unsafe_UnsafeReactivateAttributeValueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeReactivateAttributeValueRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_policy_unsafe_UnsafeReactivateAttributeValueResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_policy_unsafe_UnsafeReactivateAttributeValueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeReactivateAttributeValueResponse_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_policy_unsafe_UnsafeDeleteAttributeValueRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_policy_unsafe_UnsafeDeleteAttributeValueRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeDeleteAttributeValueRequest_descriptor,
        new java.lang.String[] { "Id", "Fqn", });
    internal_static_policy_unsafe_UnsafeDeleteAttributeValueResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_policy_unsafe_UnsafeDeleteAttributeValueResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_unsafe_UnsafeDeleteAttributeValueResponse_descriptor,
        new java.lang.String[] { "Value", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    io.opentdf.platform.policy.ObjectsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
