// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/unsafe/unsafe.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.unsafe;

public interface UnsafeDeleteAttributeValueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.unsafe.UnsafeDeleteAttributeValueRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required
   * UUID of the Attribute Value
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Required
   * UUID of the Attribute Value
   * </pre>
   *
   * <code>string id = 1 [json_name = "id", (.buf.validate.field) = { ... }</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Fully Qualified Name (FQN) of Attribute Value (i.e. https://&lt;namespace&gt;/attr/&lt;attribute name&gt;/value/&lt;value&gt;), normalized to lower case.
   * </pre>
   *
   * <code>string fqn = 2 [json_name = "fqn", (.buf.validate.field) = { ... }</code>
   * @return The fqn.
   */
  java.lang.String getFqn();
  /**
   * <pre>
   * Fully Qualified Name (FQN) of Attribute Value (i.e. https://&lt;namespace&gt;/attr/&lt;attribute name&gt;/value/&lt;value&gt;), normalized to lower case.
   * </pre>
   *
   * <code>string fqn = 2 [json_name = "fqn", (.buf.validate.field) = { ... }</code>
   * @return The bytes for fqn.
   */
  com.google.protobuf.ByteString
      getFqnBytes();
}
