// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/resourcemapping/resource_mapping.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.resourcemapping;

public interface ListResourceMappingsByGroupFqnsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.resourcemapping.ListResourceMappingsByGroupFqnsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, .policy.resourcemapping.ResourceMappingsByGroup&gt; fqn_resource_mapping_groups = 1 [json_name = "fqnResourceMappingGroups"];</code>
   */
  int getFqnResourceMappingGroupsCount();
  /**
   * <code>map&lt;string, .policy.resourcemapping.ResourceMappingsByGroup&gt; fqn_resource_mapping_groups = 1 [json_name = "fqnResourceMappingGroups"];</code>
   */
  boolean containsFqnResourceMappingGroups(
      java.lang.String key);
  /**
   * Use {@link #getFqnResourceMappingGroupsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup>
  getFqnResourceMappingGroups();
  /**
   * <code>map&lt;string, .policy.resourcemapping.ResourceMappingsByGroup&gt; fqn_resource_mapping_groups = 1 [json_name = "fqnResourceMappingGroups"];</code>
   */
  java.util.Map<java.lang.String, io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup>
  getFqnResourceMappingGroupsMap();
  /**
   * <code>map&lt;string, .policy.resourcemapping.ResourceMappingsByGroup&gt; fqn_resource_mapping_groups = 1 [json_name = "fqnResourceMappingGroups"];</code>
   */
  /* nullable */
io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup getFqnResourceMappingGroupsOrDefault(
      java.lang.String key,
      /* nullable */
io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup defaultValue);
  /**
   * <code>map&lt;string, .policy.resourcemapping.ResourceMappingsByGroup&gt; fqn_resource_mapping_groups = 1 [json_name = "fqnResourceMappingGroups"];</code>
   */
  io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup getFqnResourceMappingGroupsOrThrow(
      java.lang.String key);
}
