// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/resourcemapping/resource_mapping.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.resourcemapping;

public interface ListResourceMappingGroupsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.resourcemapping.ListResourceMappingGroupsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
   */
  java.util.List<io.opentdf.platform.policy.ResourceMappingGroup> 
      getResourceMappingGroupsList();
  /**
   * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
   */
  io.opentdf.platform.policy.ResourceMappingGroup getResourceMappingGroups(int index);
  /**
   * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
   */
  int getResourceMappingGroupsCount();
  /**
   * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
   */
  java.util.List<? extends io.opentdf.platform.policy.ResourceMappingGroupOrBuilder> 
      getResourceMappingGroupsOrBuilderList();
  /**
   * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
   */
  io.opentdf.platform.policy.ResourceMappingGroupOrBuilder getResourceMappingGroupsOrBuilder(
      int index);
}
