// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/resourcemapping/resource_mapping.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.resourcemapping;

public interface ListResourceMappingGroupsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.resourcemapping.ListResourceMappingGroupsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Optional
   * </pre>
   *
   * <code>string namespace_id = 1 [json_name = "namespaceId"];</code>
   * @return The namespaceId.
   */
  java.lang.String getNamespaceId();
  /**
   * <pre>
   * Optional
   * </pre>
   *
   * <code>string namespace_id = 1 [json_name = "namespaceId"];</code>
   * @return The bytes for namespaceId.
   */
  com.google.protobuf.ByteString
      getNamespaceIdBytes();
}
