// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/resourcemapping/resource_mapping.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.resourcemapping;

/**
 * Protobuf type {@code policy.resourcemapping.ListResourceMappingGroupsResponse}
 */
public final class ListResourceMappingGroupsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:policy.resourcemapping.ListResourceMappingGroupsResponse)
    ListResourceMappingGroupsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListResourceMappingGroupsResponse.newBuilder() to construct.
  private ListResourceMappingGroupsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListResourceMappingGroupsResponse() {
    resourceMappingGroups_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListResourceMappingGroupsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opentdf.platform.policy.resourcemapping.ResourceMappingProto.internal_static_policy_resourcemapping_ListResourceMappingGroupsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opentdf.platform.policy.resourcemapping.ResourceMappingProto.internal_static_policy_resourcemapping_ListResourceMappingGroupsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse.class, io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse.Builder.class);
  }

  public static final int RESOURCE_MAPPING_GROUPS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.opentdf.platform.policy.ResourceMappingGroup> resourceMappingGroups_;
  /**
   * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
   */
  @java.lang.Override
  public java.util.List<io.opentdf.platform.policy.ResourceMappingGroup> getResourceMappingGroupsList() {
    return resourceMappingGroups_;
  }
  /**
   * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.opentdf.platform.policy.ResourceMappingGroupOrBuilder> 
      getResourceMappingGroupsOrBuilderList() {
    return resourceMappingGroups_;
  }
  /**
   * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
   */
  @java.lang.Override
  public int getResourceMappingGroupsCount() {
    return resourceMappingGroups_.size();
  }
  /**
   * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
   */
  @java.lang.Override
  public io.opentdf.platform.policy.ResourceMappingGroup getResourceMappingGroups(int index) {
    return resourceMappingGroups_.get(index);
  }
  /**
   * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
   */
  @java.lang.Override
  public io.opentdf.platform.policy.ResourceMappingGroupOrBuilder getResourceMappingGroupsOrBuilder(
      int index) {
    return resourceMappingGroups_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < resourceMappingGroups_.size(); i++) {
      output.writeMessage(1, resourceMappingGroups_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < resourceMappingGroups_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, resourceMappingGroups_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse)) {
      return super.equals(obj);
    }
    io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse other = (io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse) obj;

    if (!getResourceMappingGroupsList()
        .equals(other.getResourceMappingGroupsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getResourceMappingGroupsCount() > 0) {
      hash = (37 * hash) + RESOURCE_MAPPING_GROUPS_FIELD_NUMBER;
      hash = (53 * hash) + getResourceMappingGroupsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code policy.resourcemapping.ListResourceMappingGroupsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:policy.resourcemapping.ListResourceMappingGroupsResponse)
      io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opentdf.platform.policy.resourcemapping.ResourceMappingProto.internal_static_policy_resourcemapping_ListResourceMappingGroupsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opentdf.platform.policy.resourcemapping.ResourceMappingProto.internal_static_policy_resourcemapping_ListResourceMappingGroupsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse.class, io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse.Builder.class);
    }

    // Construct using io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (resourceMappingGroupsBuilder_ == null) {
        resourceMappingGroups_ = java.util.Collections.emptyList();
      } else {
        resourceMappingGroups_ = null;
        resourceMappingGroupsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opentdf.platform.policy.resourcemapping.ResourceMappingProto.internal_static_policy_resourcemapping_ListResourceMappingGroupsResponse_descriptor;
    }

    @java.lang.Override
    public io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse getDefaultInstanceForType() {
      return io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse build() {
      io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse buildPartial() {
      io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse result = new io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse result) {
      if (resourceMappingGroupsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          resourceMappingGroups_ = java.util.Collections.unmodifiableList(resourceMappingGroups_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.resourceMappingGroups_ = resourceMappingGroups_;
      } else {
        result.resourceMappingGroups_ = resourceMappingGroupsBuilder_.build();
      }
    }

    private void buildPartial0(io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse) {
        return mergeFrom((io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse other) {
      if (other == io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse.getDefaultInstance()) return this;
      if (resourceMappingGroupsBuilder_ == null) {
        if (!other.resourceMappingGroups_.isEmpty()) {
          if (resourceMappingGroups_.isEmpty()) {
            resourceMappingGroups_ = other.resourceMappingGroups_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResourceMappingGroupsIsMutable();
            resourceMappingGroups_.addAll(other.resourceMappingGroups_);
          }
          onChanged();
        }
      } else {
        if (!other.resourceMappingGroups_.isEmpty()) {
          if (resourceMappingGroupsBuilder_.isEmpty()) {
            resourceMappingGroupsBuilder_.dispose();
            resourceMappingGroupsBuilder_ = null;
            resourceMappingGroups_ = other.resourceMappingGroups_;
            bitField0_ = (bitField0_ & ~0x00000001);
            resourceMappingGroupsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResourceMappingGroupsFieldBuilder() : null;
          } else {
            resourceMappingGroupsBuilder_.addAllMessages(other.resourceMappingGroups_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.opentdf.platform.policy.ResourceMappingGroup m =
                  input.readMessage(
                      io.opentdf.platform.policy.ResourceMappingGroup.parser(),
                      extensionRegistry);
              if (resourceMappingGroupsBuilder_ == null) {
                ensureResourceMappingGroupsIsMutable();
                resourceMappingGroups_.add(m);
              } else {
                resourceMappingGroupsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.opentdf.platform.policy.ResourceMappingGroup> resourceMappingGroups_ =
      java.util.Collections.emptyList();
    private void ensureResourceMappingGroupsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        resourceMappingGroups_ = new java.util.ArrayList<io.opentdf.platform.policy.ResourceMappingGroup>(resourceMappingGroups_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opentdf.platform.policy.ResourceMappingGroup, io.opentdf.platform.policy.ResourceMappingGroup.Builder, io.opentdf.platform.policy.ResourceMappingGroupOrBuilder> resourceMappingGroupsBuilder_;

    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public java.util.List<io.opentdf.platform.policy.ResourceMappingGroup> getResourceMappingGroupsList() {
      if (resourceMappingGroupsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(resourceMappingGroups_);
      } else {
        return resourceMappingGroupsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public int getResourceMappingGroupsCount() {
      if (resourceMappingGroupsBuilder_ == null) {
        return resourceMappingGroups_.size();
      } else {
        return resourceMappingGroupsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public io.opentdf.platform.policy.ResourceMappingGroup getResourceMappingGroups(int index) {
      if (resourceMappingGroupsBuilder_ == null) {
        return resourceMappingGroups_.get(index);
      } else {
        return resourceMappingGroupsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public Builder setResourceMappingGroups(
        int index, io.opentdf.platform.policy.ResourceMappingGroup value) {
      if (resourceMappingGroupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResourceMappingGroupsIsMutable();
        resourceMappingGroups_.set(index, value);
        onChanged();
      } else {
        resourceMappingGroupsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public Builder setResourceMappingGroups(
        int index, io.opentdf.platform.policy.ResourceMappingGroup.Builder builderForValue) {
      if (resourceMappingGroupsBuilder_ == null) {
        ensureResourceMappingGroupsIsMutable();
        resourceMappingGroups_.set(index, builderForValue.build());
        onChanged();
      } else {
        resourceMappingGroupsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public Builder addResourceMappingGroups(io.opentdf.platform.policy.ResourceMappingGroup value) {
      if (resourceMappingGroupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResourceMappingGroupsIsMutable();
        resourceMappingGroups_.add(value);
        onChanged();
      } else {
        resourceMappingGroupsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public Builder addResourceMappingGroups(
        int index, io.opentdf.platform.policy.ResourceMappingGroup value) {
      if (resourceMappingGroupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResourceMappingGroupsIsMutable();
        resourceMappingGroups_.add(index, value);
        onChanged();
      } else {
        resourceMappingGroupsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public Builder addResourceMappingGroups(
        io.opentdf.platform.policy.ResourceMappingGroup.Builder builderForValue) {
      if (resourceMappingGroupsBuilder_ == null) {
        ensureResourceMappingGroupsIsMutable();
        resourceMappingGroups_.add(builderForValue.build());
        onChanged();
      } else {
        resourceMappingGroupsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public Builder addResourceMappingGroups(
        int index, io.opentdf.platform.policy.ResourceMappingGroup.Builder builderForValue) {
      if (resourceMappingGroupsBuilder_ == null) {
        ensureResourceMappingGroupsIsMutable();
        resourceMappingGroups_.add(index, builderForValue.build());
        onChanged();
      } else {
        resourceMappingGroupsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public Builder addAllResourceMappingGroups(
        java.lang.Iterable<? extends io.opentdf.platform.policy.ResourceMappingGroup> values) {
      if (resourceMappingGroupsBuilder_ == null) {
        ensureResourceMappingGroupsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, resourceMappingGroups_);
        onChanged();
      } else {
        resourceMappingGroupsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public Builder clearResourceMappingGroups() {
      if (resourceMappingGroupsBuilder_ == null) {
        resourceMappingGroups_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        resourceMappingGroupsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public Builder removeResourceMappingGroups(int index) {
      if (resourceMappingGroupsBuilder_ == null) {
        ensureResourceMappingGroupsIsMutable();
        resourceMappingGroups_.remove(index);
        onChanged();
      } else {
        resourceMappingGroupsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public io.opentdf.platform.policy.ResourceMappingGroup.Builder getResourceMappingGroupsBuilder(
        int index) {
      return getResourceMappingGroupsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public io.opentdf.platform.policy.ResourceMappingGroupOrBuilder getResourceMappingGroupsOrBuilder(
        int index) {
      if (resourceMappingGroupsBuilder_ == null) {
        return resourceMappingGroups_.get(index);  } else {
        return resourceMappingGroupsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public java.util.List<? extends io.opentdf.platform.policy.ResourceMappingGroupOrBuilder> 
         getResourceMappingGroupsOrBuilderList() {
      if (resourceMappingGroupsBuilder_ != null) {
        return resourceMappingGroupsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(resourceMappingGroups_);
      }
    }
    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public io.opentdf.platform.policy.ResourceMappingGroup.Builder addResourceMappingGroupsBuilder() {
      return getResourceMappingGroupsFieldBuilder().addBuilder(
          io.opentdf.platform.policy.ResourceMappingGroup.getDefaultInstance());
    }
    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public io.opentdf.platform.policy.ResourceMappingGroup.Builder addResourceMappingGroupsBuilder(
        int index) {
      return getResourceMappingGroupsFieldBuilder().addBuilder(
          index, io.opentdf.platform.policy.ResourceMappingGroup.getDefaultInstance());
    }
    /**
     * <code>repeated .policy.ResourceMappingGroup resource_mapping_groups = 1 [json_name = "resourceMappingGroups"];</code>
     */
    public java.util.List<io.opentdf.platform.policy.ResourceMappingGroup.Builder> 
         getResourceMappingGroupsBuilderList() {
      return getResourceMappingGroupsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opentdf.platform.policy.ResourceMappingGroup, io.opentdf.platform.policy.ResourceMappingGroup.Builder, io.opentdf.platform.policy.ResourceMappingGroupOrBuilder> 
        getResourceMappingGroupsFieldBuilder() {
      if (resourceMappingGroupsBuilder_ == null) {
        resourceMappingGroupsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.opentdf.platform.policy.ResourceMappingGroup, io.opentdf.platform.policy.ResourceMappingGroup.Builder, io.opentdf.platform.policy.ResourceMappingGroupOrBuilder>(
                resourceMappingGroups_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        resourceMappingGroups_ = null;
      }
      return resourceMappingGroupsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:policy.resourcemapping.ListResourceMappingGroupsResponse)
  }

  // @@protoc_insertion_point(class_scope:policy.resourcemapping.ListResourceMappingGroupsResponse)
  private static final io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse();
  }

  public static io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListResourceMappingGroupsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListResourceMappingGroupsResponse>() {
    @java.lang.Override
    public ListResourceMappingGroupsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListResourceMappingGroupsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListResourceMappingGroupsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opentdf.platform.policy.resourcemapping.ListResourceMappingGroupsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

