// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/resourcemapping/resource_mapping.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.resourcemapping;

public interface ResourceMappingsByGroupOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.resourcemapping.ResourceMappingsByGroup)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.policy.ResourceMappingGroup group = 1 [json_name = "group"];</code>
   * @return Whether the group field is set.
   */
  boolean hasGroup();
  /**
   * <code>.policy.ResourceMappingGroup group = 1 [json_name = "group"];</code>
   * @return The group.
   */
  io.opentdf.platform.policy.ResourceMappingGroup getGroup();
  /**
   * <code>.policy.ResourceMappingGroup group = 1 [json_name = "group"];</code>
   */
  io.opentdf.platform.policy.ResourceMappingGroupOrBuilder getGroupOrBuilder();

  /**
   * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
   */
  java.util.List<io.opentdf.platform.policy.ResourceMapping> 
      getMappingsList();
  /**
   * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
   */
  io.opentdf.platform.policy.ResourceMapping getMappings(int index);
  /**
   * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
   */
  int getMappingsCount();
  /**
   * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
   */
  java.util.List<? extends io.opentdf.platform.policy.ResourceMappingOrBuilder> 
      getMappingsOrBuilderList();
  /**
   * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
   */
  io.opentdf.platform.policy.ResourceMappingOrBuilder getMappingsOrBuilder(
      int index);
}
