// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/resourcemapping/resource_mapping.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.resourcemapping;

/**
 * Protobuf type {@code policy.resourcemapping.ResourceMappingsByGroup}
 */
public final class ResourceMappingsByGroup extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:policy.resourcemapping.ResourceMappingsByGroup)
    ResourceMappingsByGroupOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResourceMappingsByGroup.newBuilder() to construct.
  private ResourceMappingsByGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResourceMappingsByGroup() {
    mappings_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResourceMappingsByGroup();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opentdf.platform.policy.resourcemapping.ResourceMappingProto.internal_static_policy_resourcemapping_ResourceMappingsByGroup_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opentdf.platform.policy.resourcemapping.ResourceMappingProto.internal_static_policy_resourcemapping_ResourceMappingsByGroup_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup.class, io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup.Builder.class);
  }

  private int bitField0_;
  public static final int GROUP_FIELD_NUMBER = 1;
  private io.opentdf.platform.policy.ResourceMappingGroup group_;
  /**
   * <code>.policy.ResourceMappingGroup group = 1 [json_name = "group"];</code>
   * @return Whether the group field is set.
   */
  @java.lang.Override
  public boolean hasGroup() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.policy.ResourceMappingGroup group = 1 [json_name = "group"];</code>
   * @return The group.
   */
  @java.lang.Override
  public io.opentdf.platform.policy.ResourceMappingGroup getGroup() {
    return group_ == null ? io.opentdf.platform.policy.ResourceMappingGroup.getDefaultInstance() : group_;
  }
  /**
   * <code>.policy.ResourceMappingGroup group = 1 [json_name = "group"];</code>
   */
  @java.lang.Override
  public io.opentdf.platform.policy.ResourceMappingGroupOrBuilder getGroupOrBuilder() {
    return group_ == null ? io.opentdf.platform.policy.ResourceMappingGroup.getDefaultInstance() : group_;
  }

  public static final int MAPPINGS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<io.opentdf.platform.policy.ResourceMapping> mappings_;
  /**
   * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
   */
  @java.lang.Override
  public java.util.List<io.opentdf.platform.policy.ResourceMapping> getMappingsList() {
    return mappings_;
  }
  /**
   * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.opentdf.platform.policy.ResourceMappingOrBuilder> 
      getMappingsOrBuilderList() {
    return mappings_;
  }
  /**
   * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
   */
  @java.lang.Override
  public int getMappingsCount() {
    return mappings_.size();
  }
  /**
   * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
   */
  @java.lang.Override
  public io.opentdf.platform.policy.ResourceMapping getMappings(int index) {
    return mappings_.get(index);
  }
  /**
   * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
   */
  @java.lang.Override
  public io.opentdf.platform.policy.ResourceMappingOrBuilder getMappingsOrBuilder(
      int index) {
    return mappings_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getGroup());
    }
    for (int i = 0; i < mappings_.size(); i++) {
      output.writeMessage(2, mappings_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getGroup());
    }
    for (int i = 0; i < mappings_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, mappings_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup)) {
      return super.equals(obj);
    }
    io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup other = (io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup) obj;

    if (hasGroup() != other.hasGroup()) return false;
    if (hasGroup()) {
      if (!getGroup()
          .equals(other.getGroup())) return false;
    }
    if (!getMappingsList()
        .equals(other.getMappingsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGroup()) {
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup().hashCode();
    }
    if (getMappingsCount() > 0) {
      hash = (37 * hash) + MAPPINGS_FIELD_NUMBER;
      hash = (53 * hash) + getMappingsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code policy.resourcemapping.ResourceMappingsByGroup}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:policy.resourcemapping.ResourceMappingsByGroup)
      io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroupOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opentdf.platform.policy.resourcemapping.ResourceMappingProto.internal_static_policy_resourcemapping_ResourceMappingsByGroup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opentdf.platform.policy.resourcemapping.ResourceMappingProto.internal_static_policy_resourcemapping_ResourceMappingsByGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup.class, io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup.Builder.class);
    }

    // Construct using io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getGroupFieldBuilder();
        getMappingsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      group_ = null;
      if (groupBuilder_ != null) {
        groupBuilder_.dispose();
        groupBuilder_ = null;
      }
      if (mappingsBuilder_ == null) {
        mappings_ = java.util.Collections.emptyList();
      } else {
        mappings_ = null;
        mappingsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opentdf.platform.policy.resourcemapping.ResourceMappingProto.internal_static_policy_resourcemapping_ResourceMappingsByGroup_descriptor;
    }

    @java.lang.Override
    public io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup getDefaultInstanceForType() {
      return io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup.getDefaultInstance();
    }

    @java.lang.Override
    public io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup build() {
      io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup buildPartial() {
      io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup result = new io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup result) {
      if (mappingsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          mappings_ = java.util.Collections.unmodifiableList(mappings_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.mappings_ = mappings_;
      } else {
        result.mappings_ = mappingsBuilder_.build();
      }
    }

    private void buildPartial0(io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.group_ = groupBuilder_ == null
            ? group_
            : groupBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup) {
        return mergeFrom((io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup other) {
      if (other == io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup.getDefaultInstance()) return this;
      if (other.hasGroup()) {
        mergeGroup(other.getGroup());
      }
      if (mappingsBuilder_ == null) {
        if (!other.mappings_.isEmpty()) {
          if (mappings_.isEmpty()) {
            mappings_ = other.mappings_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMappingsIsMutable();
            mappings_.addAll(other.mappings_);
          }
          onChanged();
        }
      } else {
        if (!other.mappings_.isEmpty()) {
          if (mappingsBuilder_.isEmpty()) {
            mappingsBuilder_.dispose();
            mappingsBuilder_ = null;
            mappings_ = other.mappings_;
            bitField0_ = (bitField0_ & ~0x00000002);
            mappingsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMappingsFieldBuilder() : null;
          } else {
            mappingsBuilder_.addAllMessages(other.mappings_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getGroupFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              io.opentdf.platform.policy.ResourceMapping m =
                  input.readMessage(
                      io.opentdf.platform.policy.ResourceMapping.parser(),
                      extensionRegistry);
              if (mappingsBuilder_ == null) {
                ensureMappingsIsMutable();
                mappings_.add(m);
              } else {
                mappingsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private io.opentdf.platform.policy.ResourceMappingGroup group_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opentdf.platform.policy.ResourceMappingGroup, io.opentdf.platform.policy.ResourceMappingGroup.Builder, io.opentdf.platform.policy.ResourceMappingGroupOrBuilder> groupBuilder_;
    /**
     * <code>.policy.ResourceMappingGroup group = 1 [json_name = "group"];</code>
     * @return Whether the group field is set.
     */
    public boolean hasGroup() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.policy.ResourceMappingGroup group = 1 [json_name = "group"];</code>
     * @return The group.
     */
    public io.opentdf.platform.policy.ResourceMappingGroup getGroup() {
      if (groupBuilder_ == null) {
        return group_ == null ? io.opentdf.platform.policy.ResourceMappingGroup.getDefaultInstance() : group_;
      } else {
        return groupBuilder_.getMessage();
      }
    }
    /**
     * <code>.policy.ResourceMappingGroup group = 1 [json_name = "group"];</code>
     */
    public Builder setGroup(io.opentdf.platform.policy.ResourceMappingGroup value) {
      if (groupBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        group_ = value;
      } else {
        groupBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.policy.ResourceMappingGroup group = 1 [json_name = "group"];</code>
     */
    public Builder setGroup(
        io.opentdf.platform.policy.ResourceMappingGroup.Builder builderForValue) {
      if (groupBuilder_ == null) {
        group_ = builderForValue.build();
      } else {
        groupBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.policy.ResourceMappingGroup group = 1 [json_name = "group"];</code>
     */
    public Builder mergeGroup(io.opentdf.platform.policy.ResourceMappingGroup value) {
      if (groupBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          group_ != null &&
          group_ != io.opentdf.platform.policy.ResourceMappingGroup.getDefaultInstance()) {
          getGroupBuilder().mergeFrom(value);
        } else {
          group_ = value;
        }
      } else {
        groupBuilder_.mergeFrom(value);
      }
      if (group_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.policy.ResourceMappingGroup group = 1 [json_name = "group"];</code>
     */
    public Builder clearGroup() {
      bitField0_ = (bitField0_ & ~0x00000001);
      group_ = null;
      if (groupBuilder_ != null) {
        groupBuilder_.dispose();
        groupBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.policy.ResourceMappingGroup group = 1 [json_name = "group"];</code>
     */
    public io.opentdf.platform.policy.ResourceMappingGroup.Builder getGroupBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getGroupFieldBuilder().getBuilder();
    }
    /**
     * <code>.policy.ResourceMappingGroup group = 1 [json_name = "group"];</code>
     */
    public io.opentdf.platform.policy.ResourceMappingGroupOrBuilder getGroupOrBuilder() {
      if (groupBuilder_ != null) {
        return groupBuilder_.getMessageOrBuilder();
      } else {
        return group_ == null ?
            io.opentdf.platform.policy.ResourceMappingGroup.getDefaultInstance() : group_;
      }
    }
    /**
     * <code>.policy.ResourceMappingGroup group = 1 [json_name = "group"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opentdf.platform.policy.ResourceMappingGroup, io.opentdf.platform.policy.ResourceMappingGroup.Builder, io.opentdf.platform.policy.ResourceMappingGroupOrBuilder> 
        getGroupFieldBuilder() {
      if (groupBuilder_ == null) {
        groupBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.opentdf.platform.policy.ResourceMappingGroup, io.opentdf.platform.policy.ResourceMappingGroup.Builder, io.opentdf.platform.policy.ResourceMappingGroupOrBuilder>(
                getGroup(),
                getParentForChildren(),
                isClean());
        group_ = null;
      }
      return groupBuilder_;
    }

    private java.util.List<io.opentdf.platform.policy.ResourceMapping> mappings_ =
      java.util.Collections.emptyList();
    private void ensureMappingsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        mappings_ = new java.util.ArrayList<io.opentdf.platform.policy.ResourceMapping>(mappings_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opentdf.platform.policy.ResourceMapping, io.opentdf.platform.policy.ResourceMapping.Builder, io.opentdf.platform.policy.ResourceMappingOrBuilder> mappingsBuilder_;

    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public java.util.List<io.opentdf.platform.policy.ResourceMapping> getMappingsList() {
      if (mappingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(mappings_);
      } else {
        return mappingsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public int getMappingsCount() {
      if (mappingsBuilder_ == null) {
        return mappings_.size();
      } else {
        return mappingsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public io.opentdf.platform.policy.ResourceMapping getMappings(int index) {
      if (mappingsBuilder_ == null) {
        return mappings_.get(index);
      } else {
        return mappingsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public Builder setMappings(
        int index, io.opentdf.platform.policy.ResourceMapping value) {
      if (mappingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMappingsIsMutable();
        mappings_.set(index, value);
        onChanged();
      } else {
        mappingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public Builder setMappings(
        int index, io.opentdf.platform.policy.ResourceMapping.Builder builderForValue) {
      if (mappingsBuilder_ == null) {
        ensureMappingsIsMutable();
        mappings_.set(index, builderForValue.build());
        onChanged();
      } else {
        mappingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public Builder addMappings(io.opentdf.platform.policy.ResourceMapping value) {
      if (mappingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMappingsIsMutable();
        mappings_.add(value);
        onChanged();
      } else {
        mappingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public Builder addMappings(
        int index, io.opentdf.platform.policy.ResourceMapping value) {
      if (mappingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMappingsIsMutable();
        mappings_.add(index, value);
        onChanged();
      } else {
        mappingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public Builder addMappings(
        io.opentdf.platform.policy.ResourceMapping.Builder builderForValue) {
      if (mappingsBuilder_ == null) {
        ensureMappingsIsMutable();
        mappings_.add(builderForValue.build());
        onChanged();
      } else {
        mappingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public Builder addMappings(
        int index, io.opentdf.platform.policy.ResourceMapping.Builder builderForValue) {
      if (mappingsBuilder_ == null) {
        ensureMappingsIsMutable();
        mappings_.add(index, builderForValue.build());
        onChanged();
      } else {
        mappingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public Builder addAllMappings(
        java.lang.Iterable<? extends io.opentdf.platform.policy.ResourceMapping> values) {
      if (mappingsBuilder_ == null) {
        ensureMappingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, mappings_);
        onChanged();
      } else {
        mappingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public Builder clearMappings() {
      if (mappingsBuilder_ == null) {
        mappings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        mappingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public Builder removeMappings(int index) {
      if (mappingsBuilder_ == null) {
        ensureMappingsIsMutable();
        mappings_.remove(index);
        onChanged();
      } else {
        mappingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public io.opentdf.platform.policy.ResourceMapping.Builder getMappingsBuilder(
        int index) {
      return getMappingsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public io.opentdf.platform.policy.ResourceMappingOrBuilder getMappingsOrBuilder(
        int index) {
      if (mappingsBuilder_ == null) {
        return mappings_.get(index);  } else {
        return mappingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public java.util.List<? extends io.opentdf.platform.policy.ResourceMappingOrBuilder> 
         getMappingsOrBuilderList() {
      if (mappingsBuilder_ != null) {
        return mappingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(mappings_);
      }
    }
    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public io.opentdf.platform.policy.ResourceMapping.Builder addMappingsBuilder() {
      return getMappingsFieldBuilder().addBuilder(
          io.opentdf.platform.policy.ResourceMapping.getDefaultInstance());
    }
    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public io.opentdf.platform.policy.ResourceMapping.Builder addMappingsBuilder(
        int index) {
      return getMappingsFieldBuilder().addBuilder(
          index, io.opentdf.platform.policy.ResourceMapping.getDefaultInstance());
    }
    /**
     * <code>repeated .policy.ResourceMapping mappings = 2 [json_name = "mappings"];</code>
     */
    public java.util.List<io.opentdf.platform.policy.ResourceMapping.Builder> 
         getMappingsBuilderList() {
      return getMappingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opentdf.platform.policy.ResourceMapping, io.opentdf.platform.policy.ResourceMapping.Builder, io.opentdf.platform.policy.ResourceMappingOrBuilder> 
        getMappingsFieldBuilder() {
      if (mappingsBuilder_ == null) {
        mappingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.opentdf.platform.policy.ResourceMapping, io.opentdf.platform.policy.ResourceMapping.Builder, io.opentdf.platform.policy.ResourceMappingOrBuilder>(
                mappings_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        mappings_ = null;
      }
      return mappingsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:policy.resourcemapping.ResourceMappingsByGroup)
  }

  // @@protoc_insertion_point(class_scope:policy.resourcemapping.ResourceMappingsByGroup)
  private static final io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup();
  }

  public static io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResourceMappingsByGroup>
      PARSER = new com.google.protobuf.AbstractParser<ResourceMappingsByGroup>() {
    @java.lang.Override
    public ResourceMappingsByGroup parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResourceMappingsByGroup> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResourceMappingsByGroup> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opentdf.platform.policy.resourcemapping.ResourceMappingsByGroup getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

