// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/resourcemapping/resource_mapping.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.resourcemapping;

public final class ResourceMappingProto {
  private ResourceMappingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_ListResourceMappingGroupsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_ListResourceMappingGroupsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_ListResourceMappingGroupsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_ListResourceMappingGroupsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_GetResourceMappingGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_GetResourceMappingGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_GetResourceMappingGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_GetResourceMappingGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_CreateResourceMappingGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_CreateResourceMappingGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_CreateResourceMappingGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_CreateResourceMappingGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_UpdateResourceMappingGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_UpdateResourceMappingGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_UpdateResourceMappingGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_UpdateResourceMappingGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_DeleteResourceMappingGroupRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_DeleteResourceMappingGroupRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_DeleteResourceMappingGroupResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_DeleteResourceMappingGroupResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_ListResourceMappingsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_ListResourceMappingsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_ListResourceMappingsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_ListResourceMappingsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_ListResourceMappingsByGroupFqnsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_ListResourceMappingsByGroupFqnsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_ResourceMappingsByGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_ResourceMappingsByGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_ListResourceMappingsByGroupFqnsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_ListResourceMappingsByGroupFqnsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_ListResourceMappingsByGroupFqnsResponse_FqnResourceMappingGroupsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_ListResourceMappingsByGroupFqnsResponse_FqnResourceMappingGroupsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_GetResourceMappingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_GetResourceMappingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_GetResourceMappingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_GetResourceMappingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_CreateResourceMappingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_CreateResourceMappingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_CreateResourceMappingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_CreateResourceMappingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_UpdateResourceMappingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_UpdateResourceMappingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_UpdateResourceMappingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_UpdateResourceMappingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_DeleteResourceMappingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_DeleteResourceMappingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_resourcemapping_DeleteResourceMappingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_resourcemapping_DeleteResourceMappingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-policy/resourcemapping/resource_mappin" +
      "g.proto\022\026policy.resourcemapping\032\033buf/val" +
      "idate/validate.proto\032\034google/api/annotat" +
      "ions.proto\032\023common/common.proto\032\024policy/" +
      "objects.proto\"E\n ListResourceMappingGrou" +
      "psRequest\022!\n\014namespace_id\030\001 \001(\tR\013namespa" +
      "ceId\"y\n!ListResourceMappingGroupsRespons" +
      "e\022T\n\027resource_mapping_groups\030\001 \003(\0132\034.pol" +
      "icy.ResourceMappingGroupR\025resourceMappin" +
      "gGroups\"8\n\036GetResourceMappingGroupReques" +
      "t\022\026\n\002id\030\001 \001(\tB\006\272H\003\310\001\001R\002id\"u\n\037GetResource" +
      "MappingGroupResponse\022R\n\026resource_mapping" +
      "_group\030\001 \001(\0132\034.policy.ResourceMappingGro" +
      "upR\024resourceMappingGroup\"\237\001\n!CreateResou" +
      "rceMappingGroupRequest\022)\n\014namespace_id\030\001" +
      " \001(\tB\006\272H\003\310\001\001R\013namespaceId\022\032\n\004name\030\002 \001(\tB" +
      "\006\272H\003\310\001\001R\004name\0223\n\010metadata\030d \001(\0132\027.common" +
      ".MetadataMutableR\010metadata\"x\n\"CreateReso" +
      "urceMappingGroupResponse\022R\n\026resource_map" +
      "ping_group\030\001 \001(\0132\034.policy.ResourceMappin" +
      "gGroupR\024resourceMappingGroup\"\375\001\n!UpdateR" +
      "esourceMappingGroupRequest\022\026\n\002id\030\001 \001(\tB\006" +
      "\272H\003\310\001\001R\002id\022!\n\014namespace_id\030\002 \001(\tR\013namesp" +
      "aceId\022\022\n\004name\030\003 \001(\tR\004name\0223\n\010metadata\030d " +
      "\001(\0132\027.common.MetadataMutableR\010metadata\022T" +
      "\n\030metadata_update_behavior\030e \001(\0162\032.commo" +
      "n.MetadataUpdateEnumR\026metadataUpdateBeha" +
      "vior\"x\n\"UpdateResourceMappingGroupRespon" +
      "se\022R\n\026resource_mapping_group\030\001 \001(\0132\034.pol" +
      "icy.ResourceMappingGroupR\024resourceMappin" +
      "gGroup\";\n!DeleteResourceMappingGroupRequ" +
      "est\022\026\n\002id\030\001 \001(\tB\006\272H\003\310\001\001R\002id\"x\n\"DeleteRes" +
      "ourceMappingGroupResponse\022R\n\026resource_ma" +
      "pping_group\030\001 \001(\0132\034.policy.ResourceMappi" +
      "ngGroupR\024resourceMappingGroup\"8\n\033ListRes" +
      "ourceMappingsRequest\022\031\n\010group_id\030\001 \001(\tR\007" +
      "groupId\"d\n\034ListResourceMappingsResponse\022" +
      "D\n\021resource_mappings\030\001 \003(\0132\027.policy.Reso" +
      "urceMappingR\020resourceMappings\"\320\002\n&ListRe" +
      "sourceMappingsByGroupFqnsRequest\022\245\002\n\004fqn" +
      "s\030\001 \003(\tB\220\002\272H\214\002\222\001\210\002\010\001\"\203\002\272\001\377\001\n\030resourcemap" +
      "pinggroup_fqn\022XResource Mapping Group FQ" +
      "N must be in the format \'https://<namesp" +
      "ace>/resm/<group name>\'\032\210\001this.matches(\'" +
      "^https://([a-zA-Z0-9]([a-zA-Z0-9\\\\-]{0,6" +
      "1}[a-zA-Z0-9])?\\\\.)+[a-zA-Z]{2,}/resm/[a" +
      "-zA-Z0-9](?:[a-zA-Z0-9_-]*[a-zA-Z0-9])?$" +
      "\')R\004fqns\"\202\001\n\027ResourceMappingsByGroup\0222\n\005" +
      "group\030\001 \001(\0132\034.policy.ResourceMappingGrou" +
      "pR\005group\0223\n\010mappings\030\002 \003(\0132\027.policy.Reso" +
      "urceMappingR\010mappings\"\306\002\n\'ListResourceMa" +
      "ppingsByGroupFqnsResponse\022\234\001\n\033fqn_resour" +
      "ce_mapping_groups\030\001 \003(\0132].policy.resourc" +
      "emapping.ListResourceMappingsByGroupFqns" +
      "Response.FqnResourceMappingGroupsEntryR\030" +
      "fqnResourceMappingGroups\032|\n\035FqnResourceM" +
      "appingGroupsEntry\022\020\n\003key\030\001 \001(\tR\003key\022E\n\005v" +
      "alue\030\002 \001(\0132/.policy.resourcemapping.Reso" +
      "urceMappingsByGroupR\005value:\0028\001\"3\n\031GetRes" +
      "ourceMappingRequest\022\026\n\002id\030\001 \001(\tB\006\272H\003\310\001\001R" +
      "\002id\"`\n\032GetResourceMappingResponse\022B\n\020res" +
      "ource_mapping\030\001 \001(\0132\027.policy.ResourceMap" +
      "pingR\017resourceMapping\"\302\001\n\034CreateResource" +
      "MappingRequest\0224\n\022attribute_value_id\030\001 \001" +
      "(\tB\006\272H\003\310\001\001R\020attributeValueId\022\034\n\005terms\030\002 " +
      "\003(\tB\006\272H\003\310\001\001R\005terms\022\031\n\010group_id\030\003 \001(\tR\007gr" +
      "oupId\0223\n\010metadata\030d \001(\0132\027.common.Metadat" +
      "aMutableR\010metadata\"c\n\035CreateResourceMapp" +
      "ingResponse\022B\n\020resource_mapping\030\001 \001(\0132\027." +
      "policy.ResourceMappingR\017resourceMapping\"" +
      "\240\002\n\034UpdateResourceMappingRequest\022\026\n\002id\030\001" +
      " \001(\tB\006\272H\003\310\001\001R\002id\022,\n\022attribute_value_id\030\004" +
      " \001(\tR\020attributeValueId\022\024\n\005terms\030\005 \003(\tR\005t" +
      "erms\022\031\n\010group_id\030\006 \001(\tR\007groupId\0223\n\010metad" +
      "ata\030d \001(\0132\027.common.MetadataMutableR\010meta" +
      "data\022T\n\030metadata_update_behavior\030e \001(\0162\032" +
      ".common.MetadataUpdateEnumR\026metadataUpda" +
      "teBehavior\"c\n\035UpdateResourceMappingRespo" +
      "nse\022B\n\020resource_mapping\030\001 \001(\0132\027.policy.R" +
      "esourceMappingR\017resourceMapping\"6\n\034Delet" +
      "eResourceMappingRequest\022\026\n\002id\030\001 \001(\tB\006\272H\003" +
      "\310\001\001R\002id\"c\n\035DeleteResourceMappingResponse" +
      "\022B\n\020resource_mapping\030\001 \001(\0132\027.policy.Reso" +
      "urceMappingR\017resourceMapping2\275\017\n\026Resourc" +
      "eMappingService\022\262\001\n\031ListResourceMappingG" +
      "roups\0228.policy.resourcemapping.ListResou" +
      "rceMappingGroupsRequest\0329.policy.resourc" +
      "emapping.ListResourceMappingGroupsRespon" +
      "se\" \202\323\344\223\002\032\022\030/resource-mapping-groups\022\261\001\n" +
      "\027GetResourceMappingGroup\0226.policy.resour" +
      "cemapping.GetResourceMappingGroupRequest" +
      "\0327.policy.resourcemapping.GetResourceMap" +
      "pingGroupResponse\"%\202\323\344\223\002\037\022\035/resource-map" +
      "ping-groups/{id}\022\270\001\n\032CreateResourceMappi" +
      "ngGroup\0229.policy.resourcemapping.CreateR" +
      "esourceMappingGroupRequest\032:.policy.reso" +
      "urcemapping.CreateResourceMappingGroupRe" +
      "sponse\"#\202\323\344\223\002\035\"\030/resource-mapping-groups" +
      ":\001*\022\275\001\n\032UpdateResourceMappingGroup\0229.pol" +
      "icy.resourcemapping.UpdateResourceMappin" +
      "gGroupRequest\032:.policy.resourcemapping.U" +
      "pdateResourceMappingGroupResponse\"(\202\323\344\223\002" +
      "\"2\035/resource-mapping-groups/{id}:\001*\022\272\001\n\032" +
      "DeleteResourceMappingGroup\0229.policy.reso" +
      "urcemapping.DeleteResourceMappingGroupRe" +
      "quest\032:.policy.resourcemapping.DeleteRes" +
      "ourceMappingGroupResponse\"%\202\323\344\223\002\037*\035/reso" +
      "urce-mapping-groups/{id}\022\235\001\n\024ListResourc" +
      "eMappings\0223.policy.resourcemapping.ListR" +
      "esourceMappingsRequest\0324.policy.resource" +
      "mapping.ListResourceMappingsResponse\"\032\202\323" +
      "\344\223\002\024\022\022/resource-mappings\022\311\001\n\037ListResourc" +
      "eMappingsByGroupFqns\022>.policy.resourcema" +
      "pping.ListResourceMappingsByGroupFqnsReq" +
      "uest\032?.policy.resourcemapping.ListResour" +
      "ceMappingsByGroupFqnsResponse\"%\202\323\344\223\002\037\022\035/" +
      "resource-mappings/group-fqns\022\234\001\n\022GetReso" +
      "urceMapping\0221.policy.resourcemapping.Get" +
      "ResourceMappingRequest\0322.policy.resource" +
      "mapping.GetResourceMappingResponse\"\037\202\323\344\223" +
      "\002\031\022\027/resource-mappings/{id}\022\243\001\n\025CreateRe" +
      "sourceMapping\0224.policy.resourcemapping.C" +
      "reateResourceMappingRequest\0325.policy.res" +
      "ourcemapping.CreateResourceMappingRespon" +
      "se\"\035\202\323\344\223\002\027\"\022/resource-mappings:\001*\022\250\001\n\025Up" +
      "dateResourceMapping\0224.policy.resourcemap" +
      "ping.UpdateResourceMappingRequest\0325.poli" +
      "cy.resourcemapping.UpdateResourceMapping" +
      "Response\"\"\202\323\344\223\002\0342\027/resource-mappings/{id" +
      "}:\001*\022\245\001\n\025DeleteResourceMapping\0224.policy." +
      "resourcemapping.DeleteResourceMappingReq" +
      "uest\0325.policy.resourcemapping.DeleteReso" +
      "urceMappingResponse\"\037\202\323\344\223\002\031*\027/resource-m" +
      "appings/{id}B\273\001\n*io.opentdf.platform.pol" +
      "icy.resourcemappingB\024ResourceMappingProt" +
      "oP\001\242\002\003PRX\252\002\026Policy.Resourcemapping\312\002\026Pol" +
      "icy\\Resourcemapping\342\002\"Policy\\Resourcemap" +
      "ping\\GPBMetadata\352\002\027Policy::Resourcemappi" +
      "ngb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          io.opentdf.platform.common.CommonProto.getDescriptor(),
          io.opentdf.platform.policy.ObjectsProto.getDescriptor(),
        });
    internal_static_policy_resourcemapping_ListResourceMappingGroupsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_policy_resourcemapping_ListResourceMappingGroupsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_ListResourceMappingGroupsRequest_descriptor,
        new java.lang.String[] { "NamespaceId", });
    internal_static_policy_resourcemapping_ListResourceMappingGroupsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_policy_resourcemapping_ListResourceMappingGroupsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_ListResourceMappingGroupsResponse_descriptor,
        new java.lang.String[] { "ResourceMappingGroups", });
    internal_static_policy_resourcemapping_GetResourceMappingGroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_policy_resourcemapping_GetResourceMappingGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_GetResourceMappingGroupRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_policy_resourcemapping_GetResourceMappingGroupResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_policy_resourcemapping_GetResourceMappingGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_GetResourceMappingGroupResponse_descriptor,
        new java.lang.String[] { "ResourceMappingGroup", });
    internal_static_policy_resourcemapping_CreateResourceMappingGroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_policy_resourcemapping_CreateResourceMappingGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_CreateResourceMappingGroupRequest_descriptor,
        new java.lang.String[] { "NamespaceId", "Name", "Metadata", });
    internal_static_policy_resourcemapping_CreateResourceMappingGroupResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_policy_resourcemapping_CreateResourceMappingGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_CreateResourceMappingGroupResponse_descriptor,
        new java.lang.String[] { "ResourceMappingGroup", });
    internal_static_policy_resourcemapping_UpdateResourceMappingGroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_policy_resourcemapping_UpdateResourceMappingGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_UpdateResourceMappingGroupRequest_descriptor,
        new java.lang.String[] { "Id", "NamespaceId", "Name", "Metadata", "MetadataUpdateBehavior", });
    internal_static_policy_resourcemapping_UpdateResourceMappingGroupResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_policy_resourcemapping_UpdateResourceMappingGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_UpdateResourceMappingGroupResponse_descriptor,
        new java.lang.String[] { "ResourceMappingGroup", });
    internal_static_policy_resourcemapping_DeleteResourceMappingGroupRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_policy_resourcemapping_DeleteResourceMappingGroupRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_DeleteResourceMappingGroupRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_policy_resourcemapping_DeleteResourceMappingGroupResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_policy_resourcemapping_DeleteResourceMappingGroupResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_DeleteResourceMappingGroupResponse_descriptor,
        new java.lang.String[] { "ResourceMappingGroup", });
    internal_static_policy_resourcemapping_ListResourceMappingsRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_policy_resourcemapping_ListResourceMappingsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_ListResourceMappingsRequest_descriptor,
        new java.lang.String[] { "GroupId", });
    internal_static_policy_resourcemapping_ListResourceMappingsResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_policy_resourcemapping_ListResourceMappingsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_ListResourceMappingsResponse_descriptor,
        new java.lang.String[] { "ResourceMappings", });
    internal_static_policy_resourcemapping_ListResourceMappingsByGroupFqnsRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_policy_resourcemapping_ListResourceMappingsByGroupFqnsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_ListResourceMappingsByGroupFqnsRequest_descriptor,
        new java.lang.String[] { "Fqns", });
    internal_static_policy_resourcemapping_ResourceMappingsByGroup_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_policy_resourcemapping_ResourceMappingsByGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_ResourceMappingsByGroup_descriptor,
        new java.lang.String[] { "Group", "Mappings", });
    internal_static_policy_resourcemapping_ListResourceMappingsByGroupFqnsResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_policy_resourcemapping_ListResourceMappingsByGroupFqnsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_ListResourceMappingsByGroupFqnsResponse_descriptor,
        new java.lang.String[] { "FqnResourceMappingGroups", });
    internal_static_policy_resourcemapping_ListResourceMappingsByGroupFqnsResponse_FqnResourceMappingGroupsEntry_descriptor =
      internal_static_policy_resourcemapping_ListResourceMappingsByGroupFqnsResponse_descriptor.getNestedTypes().get(0);
    internal_static_policy_resourcemapping_ListResourceMappingsByGroupFqnsResponse_FqnResourceMappingGroupsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_ListResourceMappingsByGroupFqnsResponse_FqnResourceMappingGroupsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_policy_resourcemapping_GetResourceMappingRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_policy_resourcemapping_GetResourceMappingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_GetResourceMappingRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_policy_resourcemapping_GetResourceMappingResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_policy_resourcemapping_GetResourceMappingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_GetResourceMappingResponse_descriptor,
        new java.lang.String[] { "ResourceMapping", });
    internal_static_policy_resourcemapping_CreateResourceMappingRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_policy_resourcemapping_CreateResourceMappingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_CreateResourceMappingRequest_descriptor,
        new java.lang.String[] { "AttributeValueId", "Terms", "GroupId", "Metadata", });
    internal_static_policy_resourcemapping_CreateResourceMappingResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_policy_resourcemapping_CreateResourceMappingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_CreateResourceMappingResponse_descriptor,
        new java.lang.String[] { "ResourceMapping", });
    internal_static_policy_resourcemapping_UpdateResourceMappingRequest_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_policy_resourcemapping_UpdateResourceMappingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_UpdateResourceMappingRequest_descriptor,
        new java.lang.String[] { "Id", "AttributeValueId", "Terms", "GroupId", "Metadata", "MetadataUpdateBehavior", });
    internal_static_policy_resourcemapping_UpdateResourceMappingResponse_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_policy_resourcemapping_UpdateResourceMappingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_UpdateResourceMappingResponse_descriptor,
        new java.lang.String[] { "ResourceMapping", });
    internal_static_policy_resourcemapping_DeleteResourceMappingRequest_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_policy_resourcemapping_DeleteResourceMappingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_DeleteResourceMappingRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_policy_resourcemapping_DeleteResourceMappingResponse_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_policy_resourcemapping_DeleteResourceMappingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_resourcemapping_DeleteResourceMappingResponse_descriptor,
        new java.lang.String[] { "ResourceMapping", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    io.opentdf.platform.common.CommonProto.getDescriptor();
    io.opentdf.platform.policy.ObjectsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
