// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/objects.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy;

public interface ConditionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.Condition)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * a selector for a field value on a flattened Entity Representation (such as from idP/LDAP)
   * </pre>
   *
   * <code>string subject_external_selector_value = 1 [json_name = "subjectExternalSelectorValue"];</code>
   * @return The subjectExternalSelectorValue.
   */
  java.lang.String getSubjectExternalSelectorValue();
  /**
   * <pre>
   * a selector for a field value on a flattened Entity Representation (such as from idP/LDAP)
   * </pre>
   *
   * <code>string subject_external_selector_value = 1 [json_name = "subjectExternalSelectorValue"];</code>
   * @return The bytes for subjectExternalSelectorValue.
   */
  com.google.protobuf.ByteString
      getSubjectExternalSelectorValueBytes();

  /**
   * <pre>
   * the evaluation operator of relation
   * </pre>
   *
   * <code>.policy.SubjectMappingOperatorEnum operator = 2 [json_name = "operator", (.buf.validate.field) = { ... }</code>
   * @return The enum numeric value on the wire for operator.
   */
  int getOperatorValue();
  /**
   * <pre>
   * the evaluation operator of relation
   * </pre>
   *
   * <code>.policy.SubjectMappingOperatorEnum operator = 2 [json_name = "operator", (.buf.validate.field) = { ... }</code>
   * @return The operator.
   */
  io.opentdf.platform.policy.SubjectMappingOperatorEnum getOperator();

  /**
   * <pre>
   * list of comparison values for the result of applying the subject_external_selector_value on a flattened Entity Representation (Subject), evaluated by the operator
   * </pre>
   *
   * <code>repeated string subject_external_values = 3 [json_name = "subjectExternalValues"];</code>
   * @return A list containing the subjectExternalValues.
   */
  java.util.List<java.lang.String>
      getSubjectExternalValuesList();
  /**
   * <pre>
   * list of comparison values for the result of applying the subject_external_selector_value on a flattened Entity Representation (Subject), evaluated by the operator
   * </pre>
   *
   * <code>repeated string subject_external_values = 3 [json_name = "subjectExternalValues"];</code>
   * @return The count of subjectExternalValues.
   */
  int getSubjectExternalValuesCount();
  /**
   * <pre>
   * list of comparison values for the result of applying the subject_external_selector_value on a flattened Entity Representation (Subject), evaluated by the operator
   * </pre>
   *
   * <code>repeated string subject_external_values = 3 [json_name = "subjectExternalValues"];</code>
   * @param index The index of the element to return.
   * @return The subjectExternalValues at the given index.
   */
  java.lang.String getSubjectExternalValues(int index);
  /**
   * <pre>
   * list of comparison values for the result of applying the subject_external_selector_value on a flattened Entity Representation (Subject), evaluated by the operator
   * </pre>
   *
   * <code>repeated string subject_external_values = 3 [json_name = "subjectExternalValues"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the subjectExternalValues at the given index.
   */
  com.google.protobuf.ByteString
      getSubjectExternalValuesBytes(int index);
}
