// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/objects.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy;

/**
 * <pre>
 * A KAS public key and some associated metadata for further identifcation
 * </pre>
 *
 * Protobuf type {@code policy.KasPublicKey}
 */
public final class KasPublicKey extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:policy.KasPublicKey)
    KasPublicKeyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use KasPublicKey.newBuilder() to construct.
  private KasPublicKey(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private KasPublicKey() {
    pem_ = "";
    kid_ = "";
    alg_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new KasPublicKey();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opentdf.platform.policy.ObjectsProto.internal_static_policy_KasPublicKey_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opentdf.platform.policy.ObjectsProto.internal_static_policy_KasPublicKey_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opentdf.platform.policy.KasPublicKey.class, io.opentdf.platform.policy.KasPublicKey.Builder.class);
  }

  public static final int PEM_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object pem_ = "";
  /**
   * <pre>
   * x509 ASN.1 content in PEM envelope, usually
   * </pre>
   *
   * <code>string pem = 1 [json_name = "pem"];</code>
   * @return The pem.
   */
  @java.lang.Override
  public java.lang.String getPem() {
    java.lang.Object ref = pem_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      pem_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * x509 ASN.1 content in PEM envelope, usually
   * </pre>
   *
   * <code>string pem = 1 [json_name = "pem"];</code>
   * @return The bytes for pem.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPemBytes() {
    java.lang.Object ref = pem_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      pem_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object kid_ = "";
  /**
   * <pre>
   * A unique string identifier for this key
   * </pre>
   *
   * <code>string kid = 2 [json_name = "kid"];</code>
   * @return The kid.
   */
  @java.lang.Override
  public java.lang.String getKid() {
    java.lang.Object ref = kid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      kid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A unique string identifier for this key
   * </pre>
   *
   * <code>string kid = 2 [json_name = "kid"];</code>
   * @return The bytes for kid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKidBytes() {
    java.lang.Object ref = kid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      kid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALG_FIELD_NUMBER = 3;
  private int alg_ = 0;
  /**
   * <pre>
   * A known algorithm type with any additional parameters encoded.
   * To start, these may be `rsa:2048` for encrypting ZTDF files and 
   * `ec:secp256r1` for nanoTDF, but more formats may be added as needed.
   * </pre>
   *
   * <code>.policy.KasPublicKeyAlgEnum alg = 3 [json_name = "alg"];</code>
   * @return The enum numeric value on the wire for alg.
   */
  @java.lang.Override public int getAlgValue() {
    return alg_;
  }
  /**
   * <pre>
   * A known algorithm type with any additional parameters encoded.
   * To start, these may be `rsa:2048` for encrypting ZTDF files and 
   * `ec:secp256r1` for nanoTDF, but more formats may be added as needed.
   * </pre>
   *
   * <code>.policy.KasPublicKeyAlgEnum alg = 3 [json_name = "alg"];</code>
   * @return The alg.
   */
  @java.lang.Override public io.opentdf.platform.policy.KasPublicKeyAlgEnum getAlg() {
    io.opentdf.platform.policy.KasPublicKeyAlgEnum result = io.opentdf.platform.policy.KasPublicKeyAlgEnum.forNumber(alg_);
    return result == null ? io.opentdf.platform.policy.KasPublicKeyAlgEnum.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pem_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, pem_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(kid_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, kid_);
    }
    if (alg_ != io.opentdf.platform.policy.KasPublicKeyAlgEnum.KAS_PUBLIC_KEY_ALG_ENUM_UNSPECIFIED.getNumber()) {
      output.writeEnum(3, alg_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pem_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, pem_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(kid_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, kid_);
    }
    if (alg_ != io.opentdf.platform.policy.KasPublicKeyAlgEnum.KAS_PUBLIC_KEY_ALG_ENUM_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, alg_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opentdf.platform.policy.KasPublicKey)) {
      return super.equals(obj);
    }
    io.opentdf.platform.policy.KasPublicKey other = (io.opentdf.platform.policy.KasPublicKey) obj;

    if (!getPem()
        .equals(other.getPem())) return false;
    if (!getKid()
        .equals(other.getKid())) return false;
    if (alg_ != other.alg_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PEM_FIELD_NUMBER;
    hash = (53 * hash) + getPem().hashCode();
    hash = (37 * hash) + KID_FIELD_NUMBER;
    hash = (53 * hash) + getKid().hashCode();
    hash = (37 * hash) + ALG_FIELD_NUMBER;
    hash = (53 * hash) + alg_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opentdf.platform.policy.KasPublicKey parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.KasPublicKey parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.KasPublicKey parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.KasPublicKey parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.KasPublicKey parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.KasPublicKey parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.KasPublicKey parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.policy.KasPublicKey parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opentdf.platform.policy.KasPublicKey parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opentdf.platform.policy.KasPublicKey parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentdf.platform.policy.KasPublicKey parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.policy.KasPublicKey parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opentdf.platform.policy.KasPublicKey prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A KAS public key and some associated metadata for further identifcation
   * </pre>
   *
   * Protobuf type {@code policy.KasPublicKey}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:policy.KasPublicKey)
      io.opentdf.platform.policy.KasPublicKeyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opentdf.platform.policy.ObjectsProto.internal_static_policy_KasPublicKey_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opentdf.platform.policy.ObjectsProto.internal_static_policy_KasPublicKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opentdf.platform.policy.KasPublicKey.class, io.opentdf.platform.policy.KasPublicKey.Builder.class);
    }

    // Construct using io.opentdf.platform.policy.KasPublicKey.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      pem_ = "";
      kid_ = "";
      alg_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opentdf.platform.policy.ObjectsProto.internal_static_policy_KasPublicKey_descriptor;
    }

    @java.lang.Override
    public io.opentdf.platform.policy.KasPublicKey getDefaultInstanceForType() {
      return io.opentdf.platform.policy.KasPublicKey.getDefaultInstance();
    }

    @java.lang.Override
    public io.opentdf.platform.policy.KasPublicKey build() {
      io.opentdf.platform.policy.KasPublicKey result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opentdf.platform.policy.KasPublicKey buildPartial() {
      io.opentdf.platform.policy.KasPublicKey result = new io.opentdf.platform.policy.KasPublicKey(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.opentdf.platform.policy.KasPublicKey result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.pem_ = pem_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.kid_ = kid_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.alg_ = alg_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opentdf.platform.policy.KasPublicKey) {
        return mergeFrom((io.opentdf.platform.policy.KasPublicKey)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opentdf.platform.policy.KasPublicKey other) {
      if (other == io.opentdf.platform.policy.KasPublicKey.getDefaultInstance()) return this;
      if (!other.getPem().isEmpty()) {
        pem_ = other.pem_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getKid().isEmpty()) {
        kid_ = other.kid_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.alg_ != 0) {
        setAlgValue(other.getAlgValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              pem_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              kid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              alg_ = input.readEnum();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object pem_ = "";
    /**
     * <pre>
     * x509 ASN.1 content in PEM envelope, usually
     * </pre>
     *
     * <code>string pem = 1 [json_name = "pem"];</code>
     * @return The pem.
     */
    public java.lang.String getPem() {
      java.lang.Object ref = pem_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pem_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * x509 ASN.1 content in PEM envelope, usually
     * </pre>
     *
     * <code>string pem = 1 [json_name = "pem"];</code>
     * @return The bytes for pem.
     */
    public com.google.protobuf.ByteString
        getPemBytes() {
      java.lang.Object ref = pem_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * x509 ASN.1 content in PEM envelope, usually
     * </pre>
     *
     * <code>string pem = 1 [json_name = "pem"];</code>
     * @param value The pem to set.
     * @return This builder for chaining.
     */
    public Builder setPem(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      pem_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * x509 ASN.1 content in PEM envelope, usually
     * </pre>
     *
     * <code>string pem = 1 [json_name = "pem"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPem() {
      pem_ = getDefaultInstance().getPem();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * x509 ASN.1 content in PEM envelope, usually
     * </pre>
     *
     * <code>string pem = 1 [json_name = "pem"];</code>
     * @param value The bytes for pem to set.
     * @return This builder for chaining.
     */
    public Builder setPemBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      pem_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object kid_ = "";
    /**
     * <pre>
     * A unique string identifier for this key
     * </pre>
     *
     * <code>string kid = 2 [json_name = "kid"];</code>
     * @return The kid.
     */
    public java.lang.String getKid() {
      java.lang.Object ref = kid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A unique string identifier for this key
     * </pre>
     *
     * <code>string kid = 2 [json_name = "kid"];</code>
     * @return The bytes for kid.
     */
    public com.google.protobuf.ByteString
        getKidBytes() {
      java.lang.Object ref = kid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A unique string identifier for this key
     * </pre>
     *
     * <code>string kid = 2 [json_name = "kid"];</code>
     * @param value The kid to set.
     * @return This builder for chaining.
     */
    public Builder setKid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      kid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A unique string identifier for this key
     * </pre>
     *
     * <code>string kid = 2 [json_name = "kid"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKid() {
      kid_ = getDefaultInstance().getKid();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A unique string identifier for this key
     * </pre>
     *
     * <code>string kid = 2 [json_name = "kid"];</code>
     * @param value The bytes for kid to set.
     * @return This builder for chaining.
     */
    public Builder setKidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      kid_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int alg_ = 0;
    /**
     * <pre>
     * A known algorithm type with any additional parameters encoded.
     * To start, these may be `rsa:2048` for encrypting ZTDF files and 
     * `ec:secp256r1` for nanoTDF, but more formats may be added as needed.
     * </pre>
     *
     * <code>.policy.KasPublicKeyAlgEnum alg = 3 [json_name = "alg"];</code>
     * @return The enum numeric value on the wire for alg.
     */
    @java.lang.Override public int getAlgValue() {
      return alg_;
    }
    /**
     * <pre>
     * A known algorithm type with any additional parameters encoded.
     * To start, these may be `rsa:2048` for encrypting ZTDF files and 
     * `ec:secp256r1` for nanoTDF, but more formats may be added as needed.
     * </pre>
     *
     * <code>.policy.KasPublicKeyAlgEnum alg = 3 [json_name = "alg"];</code>
     * @param value The enum numeric value on the wire for alg to set.
     * @return This builder for chaining.
     */
    public Builder setAlgValue(int value) {
      alg_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A known algorithm type with any additional parameters encoded.
     * To start, these may be `rsa:2048` for encrypting ZTDF files and 
     * `ec:secp256r1` for nanoTDF, but more formats may be added as needed.
     * </pre>
     *
     * <code>.policy.KasPublicKeyAlgEnum alg = 3 [json_name = "alg"];</code>
     * @return The alg.
     */
    @java.lang.Override
    public io.opentdf.platform.policy.KasPublicKeyAlgEnum getAlg() {
      io.opentdf.platform.policy.KasPublicKeyAlgEnum result = io.opentdf.platform.policy.KasPublicKeyAlgEnum.forNumber(alg_);
      return result == null ? io.opentdf.platform.policy.KasPublicKeyAlgEnum.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * A known algorithm type with any additional parameters encoded.
     * To start, these may be `rsa:2048` for encrypting ZTDF files and 
     * `ec:secp256r1` for nanoTDF, but more formats may be added as needed.
     * </pre>
     *
     * <code>.policy.KasPublicKeyAlgEnum alg = 3 [json_name = "alg"];</code>
     * @param value The alg to set.
     * @return This builder for chaining.
     */
    public Builder setAlg(io.opentdf.platform.policy.KasPublicKeyAlgEnum value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      alg_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A known algorithm type with any additional parameters encoded.
     * To start, these may be `rsa:2048` for encrypting ZTDF files and 
     * `ec:secp256r1` for nanoTDF, but more formats may be added as needed.
     * </pre>
     *
     * <code>.policy.KasPublicKeyAlgEnum alg = 3 [json_name = "alg"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAlg() {
      bitField0_ = (bitField0_ & ~0x00000004);
      alg_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:policy.KasPublicKey)
  }

  // @@protoc_insertion_point(class_scope:policy.KasPublicKey)
  private static final io.opentdf.platform.policy.KasPublicKey DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opentdf.platform.policy.KasPublicKey();
  }

  public static io.opentdf.platform.policy.KasPublicKey getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<KasPublicKey>
      PARSER = new com.google.protobuf.AbstractParser<KasPublicKey>() {
    @java.lang.Override
    public KasPublicKey parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<KasPublicKey> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<KasPublicKey> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opentdf.platform.policy.KasPublicKey getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

