// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/objects.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy;

/**
 * Protobuf enum {@code policy.KasPublicKeyAlgEnum}
 */
public enum KasPublicKeyAlgEnum
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>KAS_PUBLIC_KEY_ALG_ENUM_UNSPECIFIED = 0;</code>
   */
  KAS_PUBLIC_KEY_ALG_ENUM_UNSPECIFIED(0),
  /**
   * <code>KAS_PUBLIC_KEY_ALG_ENUM_RSA_2048 = 1;</code>
   */
  KAS_PUBLIC_KEY_ALG_ENUM_RSA_2048(1),
  /**
   * <code>KAS_PUBLIC_KEY_ALG_ENUM_EC_SECP256R1 = 5;</code>
   */
  KAS_PUBLIC_KEY_ALG_ENUM_EC_SECP256R1(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>KAS_PUBLIC_KEY_ALG_ENUM_UNSPECIFIED = 0;</code>
   */
  public static final int KAS_PUBLIC_KEY_ALG_ENUM_UNSPECIFIED_VALUE = 0;
  /**
   * <code>KAS_PUBLIC_KEY_ALG_ENUM_RSA_2048 = 1;</code>
   */
  public static final int KAS_PUBLIC_KEY_ALG_ENUM_RSA_2048_VALUE = 1;
  /**
   * <code>KAS_PUBLIC_KEY_ALG_ENUM_EC_SECP256R1 = 5;</code>
   */
  public static final int KAS_PUBLIC_KEY_ALG_ENUM_EC_SECP256R1_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static KasPublicKeyAlgEnum valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static KasPublicKeyAlgEnum forNumber(int value) {
    switch (value) {
      case 0: return KAS_PUBLIC_KEY_ALG_ENUM_UNSPECIFIED;
      case 1: return KAS_PUBLIC_KEY_ALG_ENUM_RSA_2048;
      case 5: return KAS_PUBLIC_KEY_ALG_ENUM_EC_SECP256R1;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<KasPublicKeyAlgEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      KasPublicKeyAlgEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<KasPublicKeyAlgEnum>() {
          public KasPublicKeyAlgEnum findValueByNumber(int number) {
            return KasPublicKeyAlgEnum.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.opentdf.platform.policy.ObjectsProto.getDescriptor().getEnumTypes().get(3);
  }

  private static final KasPublicKeyAlgEnum[] VALUES = values();

  public static KasPublicKeyAlgEnum valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private KasPublicKeyAlgEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:policy.KasPublicKeyAlgEnum)
}

