// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/objects.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy;

public final class ObjectsProto {
  private ObjectsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_Namespace_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_Namespace_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_Attribute_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_Attribute_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_Value_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_Value_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_Action_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_Action_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_SubjectMapping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_SubjectMapping_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_Condition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_Condition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_ConditionGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_ConditionGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_SubjectSet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_SubjectSet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_SubjectConditionSet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_SubjectConditionSet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_SubjectProperty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_SubjectProperty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_ResourceMappingGroup_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_ResourceMappingGroup_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_ResourceMapping_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_ResourceMapping_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_KeyAccessServer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_KeyAccessServer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_KasPublicKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_KasPublicKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_KasPublicKeySet_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_KasPublicKeySet_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_PublicKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_PublicKey_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024policy/objects.proto\022\006policy\032\033buf/vali" +
      "date/validate.proto\032\023common/common.proto" +
      "\032\036google/protobuf/wrappers.proto\"\324\001\n\tNam" +
      "espace\022\016\n\002id\030\001 \001(\tR\002id\022\022\n\004name\030\002 \001(\tR\004na" +
      "me\022\020\n\003fqn\030\003 \001(\tR\003fqn\0222\n\006active\030\004 \001(\0132\032.g" +
      "oogle.protobuf.BoolValueR\006active\022,\n\010meta" +
      "data\030\005 \001(\0132\020.common.MetadataR\010metadata\022/" +
      "\n\006grants\030\006 \003(\0132\027.policy.KeyAccessServerR" +
      "\006grants\"\354\002\n\tAttribute\022\016\n\002id\030\001 \001(\tR\002id\022/\n" +
      "\tnamespace\030\002 \001(\0132\021.policy.NamespaceR\tnam" +
      "espace\022\022\n\004name\030\003 \001(\tR\004name\022>\n\004rule\030\004 \001(\016" +
      "2\035.policy.AttributeRuleTypeEnumB\013\272H\010\202\001\002\020" +
      "\001\310\001\001R\004rule\022%\n\006values\030\005 \003(\0132\r.policy.Valu" +
      "eR\006values\022/\n\006grants\030\006 \003(\0132\027.policy.KeyAc" +
      "cessServerR\006grants\022\020\n\003fqn\030\007 \001(\tR\003fqn\0222\n\006" +
      "active\030\010 \001(\0132\032.google.protobuf.BoolValue" +
      "R\006active\022,\n\010metadata\030d \001(\0132\020.common.Meta" +
      "dataR\010metadata\"\325\002\n\005Value\022\016\n\002id\030\001 \001(\tR\002id" +
      "\022/\n\tattribute\030\002 \001(\0132\021.policy.AttributeR\t" +
      "attribute\022\024\n\005value\030\003 \001(\tR\005value\022/\n\006grant" +
      "s\030\005 \003(\0132\027.policy.KeyAccessServerR\006grants" +
      "\022\020\n\003fqn\030\006 \001(\tR\003fqn\0222\n\006active\030\007 \001(\0132\032.goo" +
      "gle.protobuf.BoolValueR\006active\022A\n\020subjec" +
      "t_mappings\030\010 \003(\0132\026.policy.SubjectMapping" +
      "R\017subjectMappings\022,\n\010metadata\030d \001(\0132\020.co" +
      "mmon.MetadataR\010metadataJ\004\010\004\020\005R\007members\"\326" +
      "\001\n\006Action\022;\n\010standard\030\001 \001(\0162\035.policy.Act" +
      "ion.StandardActionH\000R\010standard\022\030\n\006custom" +
      "\030\002 \001(\tH\000R\006custom\"l\n\016StandardAction\022\037\n\033ST" +
      "ANDARD_ACTION_UNSPECIFIED\020\000\022\033\n\027STANDARD_" +
      "ACTION_DECRYPT\020\001\022\034\n\030STANDARD_ACTION_TRAN" +
      "SMIT\020\002B\007\n\005value\"\201\002\n\016SubjectMapping\022\016\n\002id" +
      "\030\001 \001(\tR\002id\0226\n\017attribute_value\030\002 \001(\0132\r.po" +
      "licy.ValueR\016attributeValue\022O\n\025subject_co" +
      "ndition_set\030\003 \001(\0132\033.policy.SubjectCondit" +
      "ionSetR\023subjectConditionSet\022(\n\007actions\030\004" +
      " \003(\0132\016.policy.ActionR\007actions\022,\n\010metadat" +
      "a\030d \001(\0132\020.common.MetadataR\010metadata\"\327\001\n\t" +
      "Condition\022E\n\037subject_external_selector_v" +
      "alue\030\001 \001(\tR\034subjectExternalSelectorValue" +
      "\022K\n\010operator\030\002 \001(\0162\".policy.SubjectMappi" +
      "ngOperatorEnumB\013\272H\010\202\001\002\020\001\310\001\001R\010operator\0226\n" +
      "\027subject_external_values\030\003 \003(\tR\025subjectE" +
      "xternalValues\"\247\001\n\016ConditionGroup\022;\n\ncond" +
      "itions\030\001 \003(\0132\021.policy.ConditionB\010\272H\005\222\001\002\010" +
      "\001R\nconditions\022X\n\020boolean_operator\030\002 \001(\0162" +
      " .policy.ConditionBooleanTypeEnumB\013\272H\010\202\001" +
      "\002\020\001\310\001\001R\017booleanOperator\"Y\n\nSubjectSet\022K\n" +
      "\020condition_groups\030\001 \003(\0132\026.policy.Conditi" +
      "onGroupB\010\272H\005\222\001\002\010\001R\017conditionGroups\"\224\001\n\023S" +
      "ubjectConditionSet\022\016\n\002id\030\001 \001(\tR\002id\022?\n\014su" +
      "bject_sets\030\003 \003(\0132\022.policy.SubjectSetB\010\272H" +
      "\005\222\001\002\010\001R\013subjectSets\022,\n\010metadata\030d \001(\0132\020." +
      "common.MetadataR\010metadata\"\200\001\n\017SubjectPro" +
      "perty\022>\n\027external_selector_value\030\001 \001(\tB\006" +
      "\272H\003\310\001\001R\025externalSelectorValue\022-\n\016externa" +
      "l_value\030\002 \001(\tB\006\272H\003\310\001\001R\rexternalValue\"\233\001\n" +
      "\024ResourceMappingGroup\022\016\n\002id\030\001 \001(\tR\002id\022)\n" +
      "\014namespace_id\030\002 \001(\tB\006\272H\003\310\001\001R\013namespaceId" +
      "\022\032\n\004name\030\003 \001(\tB\006\272H\003\310\001\001R\004name\022,\n\010metadata" +
      "\030d \001(\0132\020.common.MetadataR\010metadata\"\331\001\n\017R" +
      "esourceMapping\022\016\n\002id\030\001 \001(\tR\002id\022,\n\010metada" +
      "ta\030\002 \001(\0132\020.common.MetadataR\010metadata\022>\n\017" +
      "attribute_value\030\003 \001(\0132\r.policy.ValueB\006\272H" +
      "\003\310\001\001R\016attributeValue\022\024\n\005terms\030\004 \003(\tR\005ter" +
      "ms\0222\n\005group\030\005 \001(\0132\034.policy.ResourceMappi" +
      "ngGroupR\005group\"\212\004\n\017KeyAccessServer\022\016\n\002id" +
      "\030\001 \001(\tR\002id\022\206\003\n\003uri\030\002 \001(\tB\363\002\272H\357\002\272\001\353\002\n\nuri" +
      "_format\022\317\001URI must be a valid URL (e.g.," +
      " \'https://demo.com/\') followed by additi" +
      "onal segments. Each segment must start a" +
      "nd end with an alphanumeric character, c" +
      "an contain hyphens, alphanumeric charact" +
      "ers, and slashes.\032\212\001this.matches(\'^https" +
      "://[a-zA-Z0-9]([a-zA-Z0-9\\\\-]{0,61}[a-zA" +
      "-Z0-9])?(\\\\.[a-zA-Z0-9]([a-zA-Z0-9\\\\-]{0" +
      ",61}[a-zA-Z0-9])?)*(:[0-9]+)?(/.*)?$\')R\003" +
      "uri\0220\n\npublic_key\030\003 \001(\0132\021.policy.PublicK" +
      "eyR\tpublicKey\022,\n\010metadata\030d \001(\0132\020.common" +
      ".MetadataR\010metadata\"a\n\014KasPublicKey\022\020\n\003p" +
      "em\030\001 \001(\tR\003pem\022\020\n\003kid\030\002 \001(\tR\003kid\022-\n\003alg\030\003" +
      " \001(\0162\033.policy.KasPublicKeyAlgEnumR\003alg\";" +
      "\n\017KasPublicKeySet\022(\n\004keys\030\001 \003(\0132\024.policy" +
      ".KasPublicKeyR\004keys\"\357\003\n\tPublicKey\022\204\003\n\006re" +
      "mote\030\001 \001(\tB\351\002\272H\345\002\272\001\341\002\n\nuri_format\022\317\001URI " +
      "must be a valid URL (e.g., \'https://demo" +
      ".com/\') followed by additional segments." +
      " Each segment must start and end with an" +
      " alphanumeric character, can contain hyp" +
      "hens, alphanumeric characters, and slash" +
      "es.\032\200\001this.matches(\'^https://[a-zA-Z0-9]" +
      "([a-zA-Z0-9\\\\-]{0,61}[a-zA-Z0-9])?(\\\\.[a" +
      "-zA-Z0-9]([a-zA-Z0-9\\\\-]{0,61}[a-zA-Z0-9" +
      "])?)*(/.*)?$\')H\000R\006remote\022\032\n\005local\030\002 \001(\tB" +
      "\002\030\001H\000R\005local\0221\n\006cached\030\003 \001(\0132\027.policy.Ka" +
      "sPublicKeySetH\000R\006cachedB\014\n\npublic_key*\263\001" +
      "\n\025AttributeRuleTypeEnum\022(\n$ATTRIBUTE_RUL" +
      "E_TYPE_ENUM_UNSPECIFIED\020\000\022#\n\037ATTRIBUTE_R" +
      "ULE_TYPE_ENUM_ALL_OF\020\001\022#\n\037ATTRIBUTE_RULE" +
      "_TYPE_ENUM_ANY_OF\020\002\022&\n\"ATTRIBUTE_RULE_TY" +
      "PE_ENUM_HIERARCHY\020\003*\312\001\n\032SubjectMappingOp" +
      "eratorEnum\022-\n)SUBJECT_MAPPING_OPERATOR_E" +
      "NUM_UNSPECIFIED\020\000\022$\n SUBJECT_MAPPING_OPE" +
      "RATOR_ENUM_IN\020\001\022(\n$SUBJECT_MAPPING_OPERA" +
      "TOR_ENUM_NOT_IN\020\002\022-\n)SUBJECT_MAPPING_OPE" +
      "RATOR_ENUM_IN_CONTAINS\020\003*\220\001\n\030ConditionBo" +
      "oleanTypeEnum\022+\n\'CONDITION_BOOLEAN_TYPE_" +
      "ENUM_UNSPECIFIED\020\000\022#\n\037CONDITION_BOOLEAN_" +
      "TYPE_ENUM_AND\020\001\022\"\n\036CONDITION_BOOLEAN_TYP" +
      "E_ENUM_OR\020\002*\232\001\n\023KasPublicKeyAlgEnum\022\'\n#K" +
      "AS_PUBLIC_KEY_ALG_ENUM_UNSPECIFIED\020\000\022$\n " +
      "KAS_PUBLIC_KEY_ALG_ENUM_RSA_2048\020\001\022(\n$KA" +
      "S_PUBLIC_KEY_ALG_ENUM_EC_SECP256R1\020\005\"\004\010\002" +
      "\020\004\"\004\010\006\020dBb\n\032io.opentdf.platform.policyB\014" +
      "ObjectsProtoP\001\242\002\003PXX\252\002\006Policy\312\002\006Policy\342\002" +
      "\022Policy\\GPBMetadata\352\002\006Policyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
          io.opentdf.platform.common.CommonProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_policy_Namespace_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_policy_Namespace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_Namespace_descriptor,
        new java.lang.String[] { "Id", "Name", "Fqn", "Active", "Metadata", "Grants", });
    internal_static_policy_Attribute_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_policy_Attribute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_Attribute_descriptor,
        new java.lang.String[] { "Id", "Namespace", "Name", "Rule", "Values", "Grants", "Fqn", "Active", "Metadata", });
    internal_static_policy_Value_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_policy_Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_Value_descriptor,
        new java.lang.String[] { "Id", "Attribute", "Value", "Grants", "Fqn", "Active", "SubjectMappings", "Metadata", });
    internal_static_policy_Action_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_policy_Action_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_Action_descriptor,
        new java.lang.String[] { "Standard", "Custom", "Value", });
    internal_static_policy_SubjectMapping_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_policy_SubjectMapping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_SubjectMapping_descriptor,
        new java.lang.String[] { "Id", "AttributeValue", "SubjectConditionSet", "Actions", "Metadata", });
    internal_static_policy_Condition_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_policy_Condition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_Condition_descriptor,
        new java.lang.String[] { "SubjectExternalSelectorValue", "Operator", "SubjectExternalValues", });
    internal_static_policy_ConditionGroup_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_policy_ConditionGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_ConditionGroup_descriptor,
        new java.lang.String[] { "Conditions", "BooleanOperator", });
    internal_static_policy_SubjectSet_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_policy_SubjectSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_SubjectSet_descriptor,
        new java.lang.String[] { "ConditionGroups", });
    internal_static_policy_SubjectConditionSet_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_policy_SubjectConditionSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_SubjectConditionSet_descriptor,
        new java.lang.String[] { "Id", "SubjectSets", "Metadata", });
    internal_static_policy_SubjectProperty_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_policy_SubjectProperty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_SubjectProperty_descriptor,
        new java.lang.String[] { "ExternalSelectorValue", "ExternalValue", });
    internal_static_policy_ResourceMappingGroup_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_policy_ResourceMappingGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_ResourceMappingGroup_descriptor,
        new java.lang.String[] { "Id", "NamespaceId", "Name", "Metadata", });
    internal_static_policy_ResourceMapping_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_policy_ResourceMapping_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_ResourceMapping_descriptor,
        new java.lang.String[] { "Id", "Metadata", "AttributeValue", "Terms", "Group", });
    internal_static_policy_KeyAccessServer_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_policy_KeyAccessServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_KeyAccessServer_descriptor,
        new java.lang.String[] { "Id", "Uri", "PublicKey", "Metadata", });
    internal_static_policy_KasPublicKey_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_policy_KasPublicKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_KasPublicKey_descriptor,
        new java.lang.String[] { "Pem", "Kid", "Alg", });
    internal_static_policy_KasPublicKeySet_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_policy_KasPublicKeySet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_KasPublicKeySet_descriptor,
        new java.lang.String[] { "Keys", });
    internal_static_policy_PublicKey_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_policy_PublicKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_PublicKey_descriptor,
        new java.lang.String[] { "Remote", "Local", "Cached", "PublicKey", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    build.buf.validate.ValidateProto.getDescriptor();
    io.opentdf.platform.common.CommonProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
