// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/objects.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy;

public interface SubjectPropertyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.SubjectProperty)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string external_selector_value = 1 [json_name = "externalSelectorValue", (.buf.validate.field) = { ... }</code>
   * @return The externalSelectorValue.
   */
  java.lang.String getExternalSelectorValue();
  /**
   * <code>string external_selector_value = 1 [json_name = "externalSelectorValue", (.buf.validate.field) = { ... }</code>
   * @return The bytes for externalSelectorValue.
   */
  com.google.protobuf.ByteString
      getExternalSelectorValueBytes();

  /**
   * <code>string external_value = 2 [json_name = "externalValue", (.buf.validate.field) = { ... }</code>
   * @return The externalValue.
   */
  java.lang.String getExternalValue();
  /**
   * <code>string external_value = 2 [json_name = "externalValue", (.buf.validate.field) = { ... }</code>
   * @return The bytes for externalValue.
   */
  com.google.protobuf.ByteString
      getExternalValueBytes();
}
