// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authorization/authorization.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.authorization;

public final class AuthorizationProto {
  private AuthorizationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_Token_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_Token_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_Entity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_Entity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_EntityCustom_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_EntityCustom_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_EntityChain_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_EntityChain_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_DecisionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_DecisionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_DecisionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_DecisionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_GetDecisionsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_GetDecisionsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_GetDecisionsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_GetDecisionsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_GetEntitlementsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_GetEntitlementsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_EntityEntitlements_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_EntityEntitlements_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_ResourceAttribute_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_ResourceAttribute_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_GetEntitlementsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_GetEntitlementsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_TokenDecisionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_TokenDecisionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_GetDecisionsByTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_GetDecisionsByTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_GetDecisionsByTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_GetDecisionsByTokenResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!authorization/authorization.proto\022\raut" +
      "horization\032\034google/api/annotations.proto" +
      "\032\031google/protobuf/any.proto\032\024policy/obje" +
      "cts.proto\")\n\005Token\022\016\n\002id\030\001 \001(\tR\002id\022\020\n\003jw" +
      "t\030\002 \001(\tR\003jwt\"\311\003\n\006Entity\022\016\n\002id\030\001 \001(\tR\002id\022" +
      "%\n\remail_address\030\002 \001(\tH\000R\014emailAddress\022\035" +
      "\n\tuser_name\030\003 \001(\tH\000R\010userName\022,\n\021remote_" +
      "claims_url\030\004 \001(\tH\000R\017remoteClaimsUrl\022\024\n\004u" +
      "uid\030\005 \001(\tH\000R\004uuid\022.\n\006claims\030\006 \001(\0132\024.goog" +
      "le.protobuf.AnyH\000R\006claims\0225\n\006custom\030\007 \001(" +
      "\0132\033.authorization.EntityCustomH\000R\006custom" +
      "\022\035\n\tclient_id\030\010 \001(\tH\000R\010clientId\022:\n\010categ" +
      "ory\030\t \001(\0162\036.authorization.Entity.Categor" +
      "yR\010category\"T\n\010Category\022\030\n\024CATEGORY_UNSP" +
      "ECIFIED\020\000\022\024\n\020CATEGORY_SUBJECT\020\001\022\030\n\024CATEG" +
      "ORY_ENVIRONMENT\020\002B\r\n\013entity_type\"B\n\014Enti" +
      "tyCustom\0222\n\textension\030\001 \001(\0132\024.google.pro" +
      "tobuf.AnyR\textension\"P\n\013EntityChain\022\016\n\002i" +
      "d\030\001 \001(\tR\002id\0221\n\010entities\030\002 \003(\0132\025.authoriz" +
      "ation.EntityR\010entities\"\317\001\n\017DecisionReque" +
      "st\022(\n\007actions\030\001 \003(\0132\016.policy.ActionR\007act" +
      "ions\022?\n\rentity_chains\030\002 \003(\0132\032.authorizat" +
      "ion.EntityChainR\014entityChains\022Q\n\023resourc" +
      "e_attributes\030\003 \003(\0132 .authorization.Resou" +
      "rceAttributeR\022resourceAttributes\"\316\002\n\020Dec" +
      "isionResponse\022&\n\017entity_chain_id\030\001 \001(\tR\r" +
      "entityChainId\0224\n\026resource_attributes_id\030" +
      "\002 \001(\tR\024resourceAttributesId\022&\n\006action\030\003 " +
      "\001(\0132\016.policy.ActionR\006action\022D\n\010decision\030" +
      "\004 \001(\0162(.authorization.DecisionResponse.D" +
      "ecisionR\010decision\022 \n\013obligations\030\005 \003(\tR\013" +
      "obligations\"L\n\010Decision\022\030\n\024DECISION_UNSP" +
      "ECIFIED\020\000\022\021\n\rDECISION_DENY\020\001\022\023\n\017DECISION" +
      "_PERMIT\020\002\"b\n\023GetDecisionsRequest\022K\n\021deci" +
      "sion_requests\030\001 \003(\0132\036.authorization.Deci" +
      "sionRequestR\020decisionRequests\"f\n\024GetDeci" +
      "sionsResponse\022N\n\022decision_responses\030\001 \003(" +
      "\0132\037.authorization.DecisionResponseR\021deci" +
      "sionResponses\"\372\001\n\026GetEntitlementsRequest" +
      "\0221\n\010entities\030\001 \003(\0132\025.authorization.Entit" +
      "yR\010entities\022;\n\005scope\030\002 \001(\0132 .authorizati" +
      "on.ResourceAttributeH\000R\005scope\210\001\001\022E\n\034with" +
      "_comprehensive_hierarchy\030\003 \001(\010H\001R\032withCo" +
      "mprehensiveHierarchy\210\001\001B\010\n\006_scopeB\037\n\035_wi" +
      "th_comprehensive_hierarchy\"c\n\022EntityEnti" +
      "tlements\022\033\n\tentity_id\030\001 \001(\tR\010entityId\0220\n" +
      "\024attribute_value_fqns\030\002 \003(\tR\022attributeVa" +
      "lueFqns\"{\n\021ResourceAttribute\0224\n\026resource" +
      "_attributes_id\030\001 \001(\tR\024resourceAttributes" +
      "Id\0220\n\024attribute_value_fqns\030\002 \003(\tR\022attrib" +
      "uteValueFqns\"`\n\027GetEntitlementsResponse\022" +
      "E\n\014entitlements\030\001 \003(\0132!.authorization.En" +
      "tityEntitlementsR\014entitlements\"\301\001\n\024Token" +
      "DecisionRequest\022(\n\007actions\030\001 \003(\0132\016.polic" +
      "y.ActionR\007actions\022,\n\006tokens\030\002 \003(\0132\024.auth" +
      "orization.TokenR\006tokens\022Q\n\023resource_attr" +
      "ibutes\030\003 \003(\0132 .authorization.ResourceAtt" +
      "ributeR\022resourceAttributes\"n\n\032GetDecisio" +
      "nsByTokenRequest\022P\n\021decision_requests\030\001 " +
      "\003(\0132#.authorization.TokenDecisionRequest" +
      "R\020decisionRequests\"m\n\033GetDecisionsByToke" +
      "nResponse\022N\n\022decision_responses\030\001 \003(\0132\037." +
      "authorization.DecisionResponseR\021decision" +
      "Responses2\226\003\n\024AuthorizationService\022r\n\014Ge" +
      "tDecisions\022\".authorization.GetDecisionsR" +
      "equest\032#.authorization.GetDecisionsRespo" +
      "nse\"\031\202\323\344\223\002\023\"\021/v1/authorization\022\215\001\n\023GetDe" +
      "cisionsByToken\022).authorization.GetDecisi" +
      "onsByTokenRequest\032*.authorization.GetDec" +
      "isionsByTokenResponse\"\037\202\323\344\223\002\031\"\027/v1/token" +
      "/authorization\022z\n\017GetEntitlements\022%.auth" +
      "orization.GetEntitlementsRequest\032&.autho" +
      "rization.GetEntitlementsResponse\"\030\202\323\344\223\002\022" +
      "\"\020/v1/entitlementsB\213\001\n!io.opentdf.platfo" +
      "rm.authorizationB\022AuthorizationProtoP\001\242\002" +
      "\003AXX\252\002\rAuthorization\312\002\rAuthorization\342\002\031A" +
      "uthorization\\GPBMetadata\352\002\rAuthorization" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
          io.opentdf.platform.policy.ObjectsProto.getDescriptor(),
        });
    internal_static_authorization_Token_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_authorization_Token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_Token_descriptor,
        new java.lang.String[] { "Id", "Jwt", });
    internal_static_authorization_Entity_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_authorization_Entity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_Entity_descriptor,
        new java.lang.String[] { "Id", "EmailAddress", "UserName", "RemoteClaimsUrl", "Uuid", "Claims", "Custom", "ClientId", "Category", "EntityType", });
    internal_static_authorization_EntityCustom_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_authorization_EntityCustom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_EntityCustom_descriptor,
        new java.lang.String[] { "Extension", });
    internal_static_authorization_EntityChain_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_authorization_EntityChain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_EntityChain_descriptor,
        new java.lang.String[] { "Id", "Entities", });
    internal_static_authorization_DecisionRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_authorization_DecisionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_DecisionRequest_descriptor,
        new java.lang.String[] { "Actions", "EntityChains", "ResourceAttributes", });
    internal_static_authorization_DecisionResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_authorization_DecisionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_DecisionResponse_descriptor,
        new java.lang.String[] { "EntityChainId", "ResourceAttributesId", "Action", "Decision", "Obligations", });
    internal_static_authorization_GetDecisionsRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_authorization_GetDecisionsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_GetDecisionsRequest_descriptor,
        new java.lang.String[] { "DecisionRequests", });
    internal_static_authorization_GetDecisionsResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_authorization_GetDecisionsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_GetDecisionsResponse_descriptor,
        new java.lang.String[] { "DecisionResponses", });
    internal_static_authorization_GetEntitlementsRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_authorization_GetEntitlementsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_GetEntitlementsRequest_descriptor,
        new java.lang.String[] { "Entities", "Scope", "WithComprehensiveHierarchy", });
    internal_static_authorization_EntityEntitlements_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_authorization_EntityEntitlements_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_EntityEntitlements_descriptor,
        new java.lang.String[] { "EntityId", "AttributeValueFqns", });
    internal_static_authorization_ResourceAttribute_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_authorization_ResourceAttribute_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_ResourceAttribute_descriptor,
        new java.lang.String[] { "ResourceAttributesId", "AttributeValueFqns", });
    internal_static_authorization_GetEntitlementsResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_authorization_GetEntitlementsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_GetEntitlementsResponse_descriptor,
        new java.lang.String[] { "Entitlements", });
    internal_static_authorization_TokenDecisionRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_authorization_TokenDecisionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_TokenDecisionRequest_descriptor,
        new java.lang.String[] { "Actions", "Tokens", "ResourceAttributes", });
    internal_static_authorization_GetDecisionsByTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_authorization_GetDecisionsByTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_GetDecisionsByTokenRequest_descriptor,
        new java.lang.String[] { "DecisionRequests", });
    internal_static_authorization_GetDecisionsByTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_authorization_GetDecisionsByTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_GetDecisionsByTokenResponse_descriptor,
        new java.lang.String[] { "DecisionResponses", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
    io.opentdf.platform.policy.ObjectsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
