// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authorization/authorization.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.authorization;

public interface EntityEntitlementsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authorization.EntityEntitlements)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string entity_id = 1 [json_name = "entityId"];</code>
   * @return The entityId.
   */
  java.lang.String getEntityId();
  /**
   * <code>string entity_id = 1 [json_name = "entityId"];</code>
   * @return The bytes for entityId.
   */
  com.google.protobuf.ByteString
      getEntityIdBytes();

  /**
   * <code>repeated string attribute_value_fqns = 2 [json_name = "attributeValueFqns"];</code>
   * @return A list containing the attributeValueFqns.
   */
  java.util.List<java.lang.String>
      getAttributeValueFqnsList();
  /**
   * <code>repeated string attribute_value_fqns = 2 [json_name = "attributeValueFqns"];</code>
   * @return The count of attributeValueFqns.
   */
  int getAttributeValueFqnsCount();
  /**
   * <code>repeated string attribute_value_fqns = 2 [json_name = "attributeValueFqns"];</code>
   * @param index The index of the element to return.
   * @return The attributeValueFqns at the given index.
   */
  java.lang.String getAttributeValueFqns(int index);
  /**
   * <code>repeated string attribute_value_fqns = 2 [json_name = "attributeValueFqns"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the attributeValueFqns at the given index.
   */
  com.google.protobuf.ByteString
      getAttributeValueFqnsBytes(int index);
}
