// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authorization/authorization.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.authorization;

public interface GetDecisionsByTokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authorization.GetDecisionsByTokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .authorization.TokenDecisionRequest decision_requests = 1 [json_name = "decisionRequests"];</code>
   */
  java.util.List<io.opentdf.platform.authorization.TokenDecisionRequest> 
      getDecisionRequestsList();
  /**
   * <code>repeated .authorization.TokenDecisionRequest decision_requests = 1 [json_name = "decisionRequests"];</code>
   */
  io.opentdf.platform.authorization.TokenDecisionRequest getDecisionRequests(int index);
  /**
   * <code>repeated .authorization.TokenDecisionRequest decision_requests = 1 [json_name = "decisionRequests"];</code>
   */
  int getDecisionRequestsCount();
  /**
   * <code>repeated .authorization.TokenDecisionRequest decision_requests = 1 [json_name = "decisionRequests"];</code>
   */
  java.util.List<? extends io.opentdf.platform.authorization.TokenDecisionRequestOrBuilder> 
      getDecisionRequestsOrBuilderList();
  /**
   * <code>repeated .authorization.TokenDecisionRequest decision_requests = 1 [json_name = "decisionRequests"];</code>
   */
  io.opentdf.platform.authorization.TokenDecisionRequestOrBuilder getDecisionRequestsOrBuilder(
      int index);
}
