// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entityresolution/entity_resolution.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.entityresolution;

/**
 * <pre>
 *
 *Example: Return the entity chains from the provided tokens
 *{
 *"entity_chains": [
 *{
 *"id": "tok1",
 *"entities": [
 *{
 *"clientId": "client1"
 *}
 *]
 *},
 *{
 *"id": "tok2",
 *"entities": [
 *{
 *"userName": "alice",
 *"clientId": "client2"
 *}
 *]
 *}
 *]
 *}
 * </pre>
 *
 * Protobuf type {@code entityresolution.CreateEntityChainFromJwtResponse}
 */
public final class CreateEntityChainFromJwtResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:entityresolution.CreateEntityChainFromJwtResponse)
    CreateEntityChainFromJwtResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateEntityChainFromJwtResponse.newBuilder() to construct.
  private CreateEntityChainFromJwtResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateEntityChainFromJwtResponse() {
    entityChains_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateEntityChainFromJwtResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opentdf.platform.entityresolution.EntityResolutionProto.internal_static_entityresolution_CreateEntityChainFromJwtResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opentdf.platform.entityresolution.EntityResolutionProto.internal_static_entityresolution_CreateEntityChainFromJwtResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse.class, io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse.Builder.class);
  }

  public static final int ENTITY_CHAINS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.opentdf.platform.authorization.EntityChain> entityChains_;
  /**
   * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
   */
  @java.lang.Override
  public java.util.List<io.opentdf.platform.authorization.EntityChain> getEntityChainsList() {
    return entityChains_;
  }
  /**
   * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.opentdf.platform.authorization.EntityChainOrBuilder> 
      getEntityChainsOrBuilderList() {
    return entityChains_;
  }
  /**
   * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
   */
  @java.lang.Override
  public int getEntityChainsCount() {
    return entityChains_.size();
  }
  /**
   * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
   */
  @java.lang.Override
  public io.opentdf.platform.authorization.EntityChain getEntityChains(int index) {
    return entityChains_.get(index);
  }
  /**
   * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
   */
  @java.lang.Override
  public io.opentdf.platform.authorization.EntityChainOrBuilder getEntityChainsOrBuilder(
      int index) {
    return entityChains_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < entityChains_.size(); i++) {
      output.writeMessage(1, entityChains_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < entityChains_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, entityChains_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse)) {
      return super.equals(obj);
    }
    io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse other = (io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse) obj;

    if (!getEntityChainsList()
        .equals(other.getEntityChainsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEntityChainsCount() > 0) {
      hash = (37 * hash) + ENTITY_CHAINS_FIELD_NUMBER;
      hash = (53 * hash) + getEntityChainsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *
   *Example: Return the entity chains from the provided tokens
   *{
   *"entity_chains": [
   *{
   *"id": "tok1",
   *"entities": [
   *{
   *"clientId": "client1"
   *}
   *]
   *},
   *{
   *"id": "tok2",
   *"entities": [
   *{
   *"userName": "alice",
   *"clientId": "client2"
   *}
   *]
   *}
   *]
   *}
   * </pre>
   *
   * Protobuf type {@code entityresolution.CreateEntityChainFromJwtResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:entityresolution.CreateEntityChainFromJwtResponse)
      io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opentdf.platform.entityresolution.EntityResolutionProto.internal_static_entityresolution_CreateEntityChainFromJwtResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opentdf.platform.entityresolution.EntityResolutionProto.internal_static_entityresolution_CreateEntityChainFromJwtResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse.class, io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse.Builder.class);
    }

    // Construct using io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (entityChainsBuilder_ == null) {
        entityChains_ = java.util.Collections.emptyList();
      } else {
        entityChains_ = null;
        entityChainsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opentdf.platform.entityresolution.EntityResolutionProto.internal_static_entityresolution_CreateEntityChainFromJwtResponse_descriptor;
    }

    @java.lang.Override
    public io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse getDefaultInstanceForType() {
      return io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse build() {
      io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse buildPartial() {
      io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse result = new io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse result) {
      if (entityChainsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          entityChains_ = java.util.Collections.unmodifiableList(entityChains_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.entityChains_ = entityChains_;
      } else {
        result.entityChains_ = entityChainsBuilder_.build();
      }
    }

    private void buildPartial0(io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse) {
        return mergeFrom((io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse other) {
      if (other == io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse.getDefaultInstance()) return this;
      if (entityChainsBuilder_ == null) {
        if (!other.entityChains_.isEmpty()) {
          if (entityChains_.isEmpty()) {
            entityChains_ = other.entityChains_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEntityChainsIsMutable();
            entityChains_.addAll(other.entityChains_);
          }
          onChanged();
        }
      } else {
        if (!other.entityChains_.isEmpty()) {
          if (entityChainsBuilder_.isEmpty()) {
            entityChainsBuilder_.dispose();
            entityChainsBuilder_ = null;
            entityChains_ = other.entityChains_;
            bitField0_ = (bitField0_ & ~0x00000001);
            entityChainsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEntityChainsFieldBuilder() : null;
          } else {
            entityChainsBuilder_.addAllMessages(other.entityChains_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.opentdf.platform.authorization.EntityChain m =
                  input.readMessage(
                      io.opentdf.platform.authorization.EntityChain.parser(),
                      extensionRegistry);
              if (entityChainsBuilder_ == null) {
                ensureEntityChainsIsMutable();
                entityChains_.add(m);
              } else {
                entityChainsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.opentdf.platform.authorization.EntityChain> entityChains_ =
      java.util.Collections.emptyList();
    private void ensureEntityChainsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        entityChains_ = new java.util.ArrayList<io.opentdf.platform.authorization.EntityChain>(entityChains_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opentdf.platform.authorization.EntityChain, io.opentdf.platform.authorization.EntityChain.Builder, io.opentdf.platform.authorization.EntityChainOrBuilder> entityChainsBuilder_;

    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public java.util.List<io.opentdf.platform.authorization.EntityChain> getEntityChainsList() {
      if (entityChainsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(entityChains_);
      } else {
        return entityChainsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public int getEntityChainsCount() {
      if (entityChainsBuilder_ == null) {
        return entityChains_.size();
      } else {
        return entityChainsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public io.opentdf.platform.authorization.EntityChain getEntityChains(int index) {
      if (entityChainsBuilder_ == null) {
        return entityChains_.get(index);
      } else {
        return entityChainsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public Builder setEntityChains(
        int index, io.opentdf.platform.authorization.EntityChain value) {
      if (entityChainsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntityChainsIsMutable();
        entityChains_.set(index, value);
        onChanged();
      } else {
        entityChainsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public Builder setEntityChains(
        int index, io.opentdf.platform.authorization.EntityChain.Builder builderForValue) {
      if (entityChainsBuilder_ == null) {
        ensureEntityChainsIsMutable();
        entityChains_.set(index, builderForValue.build());
        onChanged();
      } else {
        entityChainsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public Builder addEntityChains(io.opentdf.platform.authorization.EntityChain value) {
      if (entityChainsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntityChainsIsMutable();
        entityChains_.add(value);
        onChanged();
      } else {
        entityChainsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public Builder addEntityChains(
        int index, io.opentdf.platform.authorization.EntityChain value) {
      if (entityChainsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntityChainsIsMutable();
        entityChains_.add(index, value);
        onChanged();
      } else {
        entityChainsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public Builder addEntityChains(
        io.opentdf.platform.authorization.EntityChain.Builder builderForValue) {
      if (entityChainsBuilder_ == null) {
        ensureEntityChainsIsMutable();
        entityChains_.add(builderForValue.build());
        onChanged();
      } else {
        entityChainsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public Builder addEntityChains(
        int index, io.opentdf.platform.authorization.EntityChain.Builder builderForValue) {
      if (entityChainsBuilder_ == null) {
        ensureEntityChainsIsMutable();
        entityChains_.add(index, builderForValue.build());
        onChanged();
      } else {
        entityChainsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public Builder addAllEntityChains(
        java.lang.Iterable<? extends io.opentdf.platform.authorization.EntityChain> values) {
      if (entityChainsBuilder_ == null) {
        ensureEntityChainsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entityChains_);
        onChanged();
      } else {
        entityChainsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public Builder clearEntityChains() {
      if (entityChainsBuilder_ == null) {
        entityChains_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        entityChainsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public Builder removeEntityChains(int index) {
      if (entityChainsBuilder_ == null) {
        ensureEntityChainsIsMutable();
        entityChains_.remove(index);
        onChanged();
      } else {
        entityChainsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public io.opentdf.platform.authorization.EntityChain.Builder getEntityChainsBuilder(
        int index) {
      return getEntityChainsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public io.opentdf.platform.authorization.EntityChainOrBuilder getEntityChainsOrBuilder(
        int index) {
      if (entityChainsBuilder_ == null) {
        return entityChains_.get(index);  } else {
        return entityChainsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public java.util.List<? extends io.opentdf.platform.authorization.EntityChainOrBuilder> 
         getEntityChainsOrBuilderList() {
      if (entityChainsBuilder_ != null) {
        return entityChainsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entityChains_);
      }
    }
    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public io.opentdf.platform.authorization.EntityChain.Builder addEntityChainsBuilder() {
      return getEntityChainsFieldBuilder().addBuilder(
          io.opentdf.platform.authorization.EntityChain.getDefaultInstance());
    }
    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public io.opentdf.platform.authorization.EntityChain.Builder addEntityChainsBuilder(
        int index) {
      return getEntityChainsFieldBuilder().addBuilder(
          index, io.opentdf.platform.authorization.EntityChain.getDefaultInstance());
    }
    /**
     * <code>repeated .authorization.EntityChain entity_chains = 1 [json_name = "entityChains"];</code>
     */
    public java.util.List<io.opentdf.platform.authorization.EntityChain.Builder> 
         getEntityChainsBuilderList() {
      return getEntityChainsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opentdf.platform.authorization.EntityChain, io.opentdf.platform.authorization.EntityChain.Builder, io.opentdf.platform.authorization.EntityChainOrBuilder> 
        getEntityChainsFieldBuilder() {
      if (entityChainsBuilder_ == null) {
        entityChainsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.opentdf.platform.authorization.EntityChain, io.opentdf.platform.authorization.EntityChain.Builder, io.opentdf.platform.authorization.EntityChainOrBuilder>(
                entityChains_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        entityChains_ = null;
      }
      return entityChainsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:entityresolution.CreateEntityChainFromJwtResponse)
  }

  // @@protoc_insertion_point(class_scope:entityresolution.CreateEntityChainFromJwtResponse)
  private static final io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse();
  }

  public static io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateEntityChainFromJwtResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateEntityChainFromJwtResponse>() {
    @java.lang.Override
    public CreateEntityChainFromJwtResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateEntityChainFromJwtResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateEntityChainFromJwtResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opentdf.platform.entityresolution.CreateEntityChainFromJwtResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

