// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entityresolution/entity_resolution.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.entityresolution;

public interface ResolveEntitiesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:entityresolution.ResolveEntitiesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .authorization.Entity entities = 1 [json_name = "entities"];</code>
   */
  java.util.List<io.opentdf.platform.authorization.Entity> 
      getEntitiesList();
  /**
   * <code>repeated .authorization.Entity entities = 1 [json_name = "entities"];</code>
   */
  io.opentdf.platform.authorization.Entity getEntities(int index);
  /**
   * <code>repeated .authorization.Entity entities = 1 [json_name = "entities"];</code>
   */
  int getEntitiesCount();
  /**
   * <code>repeated .authorization.Entity entities = 1 [json_name = "entities"];</code>
   */
  java.util.List<? extends io.opentdf.platform.authorization.EntityOrBuilder> 
      getEntitiesOrBuilderList();
  /**
   * <code>repeated .authorization.Entity entities = 1 [json_name = "entities"];</code>
   */
  io.opentdf.platform.authorization.EntityOrBuilder getEntitiesOrBuilder(
      int index);
}
