// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entityresolution/entity_resolution.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.entityresolution;

public interface ResolveEntitiesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:entityresolution.ResolveEntitiesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
   */
  java.util.List<io.opentdf.platform.entityresolution.EntityRepresentation> 
      getEntityRepresentationsList();
  /**
   * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
   */
  io.opentdf.platform.entityresolution.EntityRepresentation getEntityRepresentations(int index);
  /**
   * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
   */
  int getEntityRepresentationsCount();
  /**
   * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
   */
  java.util.List<? extends io.opentdf.platform.entityresolution.EntityRepresentationOrBuilder> 
      getEntityRepresentationsOrBuilderList();
  /**
   * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
   */
  io.opentdf.platform.entityresolution.EntityRepresentationOrBuilder getEntityRepresentationsOrBuilder(
      int index);
}
