// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entityresolution/entity_resolution.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.entityresolution;

/**
 * <pre>
 *
 *Example: Get idp attributes for bob and alice
 *{
 *"entity_representations": [
 *{
 *"idp_entity_id": "e1",
 *"additional_props": {"someAttr1":"someValue1"}
 *},
 *{
 *"idp_entity_id": "e2",
 *"additional_props": {"someAttr2":"someValue2"}
 *}
 *]
 *}
 * </pre>
 *
 * Protobuf type {@code entityresolution.ResolveEntitiesResponse}
 */
public final class ResolveEntitiesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:entityresolution.ResolveEntitiesResponse)
    ResolveEntitiesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResolveEntitiesResponse.newBuilder() to construct.
  private ResolveEntitiesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResolveEntitiesResponse() {
    entityRepresentations_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ResolveEntitiesResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opentdf.platform.entityresolution.EntityResolutionProto.internal_static_entityresolution_ResolveEntitiesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opentdf.platform.entityresolution.EntityResolutionProto.internal_static_entityresolution_ResolveEntitiesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opentdf.platform.entityresolution.ResolveEntitiesResponse.class, io.opentdf.platform.entityresolution.ResolveEntitiesResponse.Builder.class);
  }

  public static final int ENTITY_REPRESENTATIONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.opentdf.platform.entityresolution.EntityRepresentation> entityRepresentations_;
  /**
   * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
   */
  @java.lang.Override
  public java.util.List<io.opentdf.platform.entityresolution.EntityRepresentation> getEntityRepresentationsList() {
    return entityRepresentations_;
  }
  /**
   * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.opentdf.platform.entityresolution.EntityRepresentationOrBuilder> 
      getEntityRepresentationsOrBuilderList() {
    return entityRepresentations_;
  }
  /**
   * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
   */
  @java.lang.Override
  public int getEntityRepresentationsCount() {
    return entityRepresentations_.size();
  }
  /**
   * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
   */
  @java.lang.Override
  public io.opentdf.platform.entityresolution.EntityRepresentation getEntityRepresentations(int index) {
    return entityRepresentations_.get(index);
  }
  /**
   * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
   */
  @java.lang.Override
  public io.opentdf.platform.entityresolution.EntityRepresentationOrBuilder getEntityRepresentationsOrBuilder(
      int index) {
    return entityRepresentations_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < entityRepresentations_.size(); i++) {
      output.writeMessage(1, entityRepresentations_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < entityRepresentations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, entityRepresentations_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opentdf.platform.entityresolution.ResolveEntitiesResponse)) {
      return super.equals(obj);
    }
    io.opentdf.platform.entityresolution.ResolveEntitiesResponse other = (io.opentdf.platform.entityresolution.ResolveEntitiesResponse) obj;

    if (!getEntityRepresentationsList()
        .equals(other.getEntityRepresentationsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEntityRepresentationsCount() > 0) {
      hash = (37 * hash) + ENTITY_REPRESENTATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getEntityRepresentationsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opentdf.platform.entityresolution.ResolveEntitiesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.entityresolution.ResolveEntitiesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.entityresolution.ResolveEntitiesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.entityresolution.ResolveEntitiesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.entityresolution.ResolveEntitiesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.entityresolution.ResolveEntitiesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.entityresolution.ResolveEntitiesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.entityresolution.ResolveEntitiesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opentdf.platform.entityresolution.ResolveEntitiesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opentdf.platform.entityresolution.ResolveEntitiesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentdf.platform.entityresolution.ResolveEntitiesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.entityresolution.ResolveEntitiesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opentdf.platform.entityresolution.ResolveEntitiesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *
   *Example: Get idp attributes for bob and alice
   *{
   *"entity_representations": [
   *{
   *"idp_entity_id": "e1",
   *"additional_props": {"someAttr1":"someValue1"}
   *},
   *{
   *"idp_entity_id": "e2",
   *"additional_props": {"someAttr2":"someValue2"}
   *}
   *]
   *}
   * </pre>
   *
   * Protobuf type {@code entityresolution.ResolveEntitiesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:entityresolution.ResolveEntitiesResponse)
      io.opentdf.platform.entityresolution.ResolveEntitiesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opentdf.platform.entityresolution.EntityResolutionProto.internal_static_entityresolution_ResolveEntitiesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opentdf.platform.entityresolution.EntityResolutionProto.internal_static_entityresolution_ResolveEntitiesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opentdf.platform.entityresolution.ResolveEntitiesResponse.class, io.opentdf.platform.entityresolution.ResolveEntitiesResponse.Builder.class);
    }

    // Construct using io.opentdf.platform.entityresolution.ResolveEntitiesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (entityRepresentationsBuilder_ == null) {
        entityRepresentations_ = java.util.Collections.emptyList();
      } else {
        entityRepresentations_ = null;
        entityRepresentationsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opentdf.platform.entityresolution.EntityResolutionProto.internal_static_entityresolution_ResolveEntitiesResponse_descriptor;
    }

    @java.lang.Override
    public io.opentdf.platform.entityresolution.ResolveEntitiesResponse getDefaultInstanceForType() {
      return io.opentdf.platform.entityresolution.ResolveEntitiesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.opentdf.platform.entityresolution.ResolveEntitiesResponse build() {
      io.opentdf.platform.entityresolution.ResolveEntitiesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opentdf.platform.entityresolution.ResolveEntitiesResponse buildPartial() {
      io.opentdf.platform.entityresolution.ResolveEntitiesResponse result = new io.opentdf.platform.entityresolution.ResolveEntitiesResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.opentdf.platform.entityresolution.ResolveEntitiesResponse result) {
      if (entityRepresentationsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          entityRepresentations_ = java.util.Collections.unmodifiableList(entityRepresentations_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.entityRepresentations_ = entityRepresentations_;
      } else {
        result.entityRepresentations_ = entityRepresentationsBuilder_.build();
      }
    }

    private void buildPartial0(io.opentdf.platform.entityresolution.ResolveEntitiesResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opentdf.platform.entityresolution.ResolveEntitiesResponse) {
        return mergeFrom((io.opentdf.platform.entityresolution.ResolveEntitiesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opentdf.platform.entityresolution.ResolveEntitiesResponse other) {
      if (other == io.opentdf.platform.entityresolution.ResolveEntitiesResponse.getDefaultInstance()) return this;
      if (entityRepresentationsBuilder_ == null) {
        if (!other.entityRepresentations_.isEmpty()) {
          if (entityRepresentations_.isEmpty()) {
            entityRepresentations_ = other.entityRepresentations_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEntityRepresentationsIsMutable();
            entityRepresentations_.addAll(other.entityRepresentations_);
          }
          onChanged();
        }
      } else {
        if (!other.entityRepresentations_.isEmpty()) {
          if (entityRepresentationsBuilder_.isEmpty()) {
            entityRepresentationsBuilder_.dispose();
            entityRepresentationsBuilder_ = null;
            entityRepresentations_ = other.entityRepresentations_;
            bitField0_ = (bitField0_ & ~0x00000001);
            entityRepresentationsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEntityRepresentationsFieldBuilder() : null;
          } else {
            entityRepresentationsBuilder_.addAllMessages(other.entityRepresentations_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.opentdf.platform.entityresolution.EntityRepresentation m =
                  input.readMessage(
                      io.opentdf.platform.entityresolution.EntityRepresentation.parser(),
                      extensionRegistry);
              if (entityRepresentationsBuilder_ == null) {
                ensureEntityRepresentationsIsMutable();
                entityRepresentations_.add(m);
              } else {
                entityRepresentationsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.opentdf.platform.entityresolution.EntityRepresentation> entityRepresentations_ =
      java.util.Collections.emptyList();
    private void ensureEntityRepresentationsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        entityRepresentations_ = new java.util.ArrayList<io.opentdf.platform.entityresolution.EntityRepresentation>(entityRepresentations_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opentdf.platform.entityresolution.EntityRepresentation, io.opentdf.platform.entityresolution.EntityRepresentation.Builder, io.opentdf.platform.entityresolution.EntityRepresentationOrBuilder> entityRepresentationsBuilder_;

    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public java.util.List<io.opentdf.platform.entityresolution.EntityRepresentation> getEntityRepresentationsList() {
      if (entityRepresentationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(entityRepresentations_);
      } else {
        return entityRepresentationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public int getEntityRepresentationsCount() {
      if (entityRepresentationsBuilder_ == null) {
        return entityRepresentations_.size();
      } else {
        return entityRepresentationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public io.opentdf.platform.entityresolution.EntityRepresentation getEntityRepresentations(int index) {
      if (entityRepresentationsBuilder_ == null) {
        return entityRepresentations_.get(index);
      } else {
        return entityRepresentationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public Builder setEntityRepresentations(
        int index, io.opentdf.platform.entityresolution.EntityRepresentation value) {
      if (entityRepresentationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntityRepresentationsIsMutable();
        entityRepresentations_.set(index, value);
        onChanged();
      } else {
        entityRepresentationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public Builder setEntityRepresentations(
        int index, io.opentdf.platform.entityresolution.EntityRepresentation.Builder builderForValue) {
      if (entityRepresentationsBuilder_ == null) {
        ensureEntityRepresentationsIsMutable();
        entityRepresentations_.set(index, builderForValue.build());
        onChanged();
      } else {
        entityRepresentationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public Builder addEntityRepresentations(io.opentdf.platform.entityresolution.EntityRepresentation value) {
      if (entityRepresentationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntityRepresentationsIsMutable();
        entityRepresentations_.add(value);
        onChanged();
      } else {
        entityRepresentationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public Builder addEntityRepresentations(
        int index, io.opentdf.platform.entityresolution.EntityRepresentation value) {
      if (entityRepresentationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntityRepresentationsIsMutable();
        entityRepresentations_.add(index, value);
        onChanged();
      } else {
        entityRepresentationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public Builder addEntityRepresentations(
        io.opentdf.platform.entityresolution.EntityRepresentation.Builder builderForValue) {
      if (entityRepresentationsBuilder_ == null) {
        ensureEntityRepresentationsIsMutable();
        entityRepresentations_.add(builderForValue.build());
        onChanged();
      } else {
        entityRepresentationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public Builder addEntityRepresentations(
        int index, io.opentdf.platform.entityresolution.EntityRepresentation.Builder builderForValue) {
      if (entityRepresentationsBuilder_ == null) {
        ensureEntityRepresentationsIsMutable();
        entityRepresentations_.add(index, builderForValue.build());
        onChanged();
      } else {
        entityRepresentationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public Builder addAllEntityRepresentations(
        java.lang.Iterable<? extends io.opentdf.platform.entityresolution.EntityRepresentation> values) {
      if (entityRepresentationsBuilder_ == null) {
        ensureEntityRepresentationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entityRepresentations_);
        onChanged();
      } else {
        entityRepresentationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public Builder clearEntityRepresentations() {
      if (entityRepresentationsBuilder_ == null) {
        entityRepresentations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        entityRepresentationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public Builder removeEntityRepresentations(int index) {
      if (entityRepresentationsBuilder_ == null) {
        ensureEntityRepresentationsIsMutable();
        entityRepresentations_.remove(index);
        onChanged();
      } else {
        entityRepresentationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public io.opentdf.platform.entityresolution.EntityRepresentation.Builder getEntityRepresentationsBuilder(
        int index) {
      return getEntityRepresentationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public io.opentdf.platform.entityresolution.EntityRepresentationOrBuilder getEntityRepresentationsOrBuilder(
        int index) {
      if (entityRepresentationsBuilder_ == null) {
        return entityRepresentations_.get(index);  } else {
        return entityRepresentationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public java.util.List<? extends io.opentdf.platform.entityresolution.EntityRepresentationOrBuilder> 
         getEntityRepresentationsOrBuilderList() {
      if (entityRepresentationsBuilder_ != null) {
        return entityRepresentationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entityRepresentations_);
      }
    }
    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public io.opentdf.platform.entityresolution.EntityRepresentation.Builder addEntityRepresentationsBuilder() {
      return getEntityRepresentationsFieldBuilder().addBuilder(
          io.opentdf.platform.entityresolution.EntityRepresentation.getDefaultInstance());
    }
    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public io.opentdf.platform.entityresolution.EntityRepresentation.Builder addEntityRepresentationsBuilder(
        int index) {
      return getEntityRepresentationsFieldBuilder().addBuilder(
          index, io.opentdf.platform.entityresolution.EntityRepresentation.getDefaultInstance());
    }
    /**
     * <code>repeated .entityresolution.EntityRepresentation entity_representations = 1 [json_name = "entityRepresentations"];</code>
     */
    public java.util.List<io.opentdf.platform.entityresolution.EntityRepresentation.Builder> 
         getEntityRepresentationsBuilderList() {
      return getEntityRepresentationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opentdf.platform.entityresolution.EntityRepresentation, io.opentdf.platform.entityresolution.EntityRepresentation.Builder, io.opentdf.platform.entityresolution.EntityRepresentationOrBuilder> 
        getEntityRepresentationsFieldBuilder() {
      if (entityRepresentationsBuilder_ == null) {
        entityRepresentationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.opentdf.platform.entityresolution.EntityRepresentation, io.opentdf.platform.entityresolution.EntityRepresentation.Builder, io.opentdf.platform.entityresolution.EntityRepresentationOrBuilder>(
                entityRepresentations_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        entityRepresentations_ = null;
      }
      return entityRepresentationsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:entityresolution.ResolveEntitiesResponse)
  }

  // @@protoc_insertion_point(class_scope:entityresolution.ResolveEntitiesResponse)
  private static final io.opentdf.platform.entityresolution.ResolveEntitiesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opentdf.platform.entityresolution.ResolveEntitiesResponse();
  }

  public static io.opentdf.platform.entityresolution.ResolveEntitiesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResolveEntitiesResponse>
      PARSER = new com.google.protobuf.AbstractParser<ResolveEntitiesResponse>() {
    @java.lang.Override
    public ResolveEntitiesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResolveEntitiesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResolveEntitiesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opentdf.platform.entityresolution.ResolveEntitiesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

