// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/kasregistry/key_access_server_registry.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.kasregistry;

public interface KeyAccessServerGrantsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.kasregistry.KeyAccessServerGrants)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.policy.KeyAccessServer key_access_server = 1 [json_name = "keyAccessServer"];</code>
   * @return Whether the keyAccessServer field is set.
   */
  boolean hasKeyAccessServer();
  /**
   * <code>.policy.KeyAccessServer key_access_server = 1 [json_name = "keyAccessServer"];</code>
   * @return The keyAccessServer.
   */
  io.opentdf.platform.policy.KeyAccessServer getKeyAccessServer();
  /**
   * <code>.policy.KeyAccessServer key_access_server = 1 [json_name = "keyAccessServer"];</code>
   */
  io.opentdf.platform.policy.KeyAccessServerOrBuilder getKeyAccessServerOrBuilder();

  /**
   * <code>repeated .policy.kasregistry.GrantedPolicyObject namespace_grants = 2 [json_name = "namespaceGrants"];</code>
   */
  java.util.List<io.opentdf.platform.policy.kasregistry.GrantedPolicyObject> 
      getNamespaceGrantsList();
  /**
   * <code>repeated .policy.kasregistry.GrantedPolicyObject namespace_grants = 2 [json_name = "namespaceGrants"];</code>
   */
  io.opentdf.platform.policy.kasregistry.GrantedPolicyObject getNamespaceGrants(int index);
  /**
   * <code>repeated .policy.kasregistry.GrantedPolicyObject namespace_grants = 2 [json_name = "namespaceGrants"];</code>
   */
  int getNamespaceGrantsCount();
  /**
   * <code>repeated .policy.kasregistry.GrantedPolicyObject namespace_grants = 2 [json_name = "namespaceGrants"];</code>
   */
  java.util.List<? extends io.opentdf.platform.policy.kasregistry.GrantedPolicyObjectOrBuilder> 
      getNamespaceGrantsOrBuilderList();
  /**
   * <code>repeated .policy.kasregistry.GrantedPolicyObject namespace_grants = 2 [json_name = "namespaceGrants"];</code>
   */
  io.opentdf.platform.policy.kasregistry.GrantedPolicyObjectOrBuilder getNamespaceGrantsOrBuilder(
      int index);

  /**
   * <code>repeated .policy.kasregistry.GrantedPolicyObject attribute_grants = 3 [json_name = "attributeGrants"];</code>
   */
  java.util.List<io.opentdf.platform.policy.kasregistry.GrantedPolicyObject> 
      getAttributeGrantsList();
  /**
   * <code>repeated .policy.kasregistry.GrantedPolicyObject attribute_grants = 3 [json_name = "attributeGrants"];</code>
   */
  io.opentdf.platform.policy.kasregistry.GrantedPolicyObject getAttributeGrants(int index);
  /**
   * <code>repeated .policy.kasregistry.GrantedPolicyObject attribute_grants = 3 [json_name = "attributeGrants"];</code>
   */
  int getAttributeGrantsCount();
  /**
   * <code>repeated .policy.kasregistry.GrantedPolicyObject attribute_grants = 3 [json_name = "attributeGrants"];</code>
   */
  java.util.List<? extends io.opentdf.platform.policy.kasregistry.GrantedPolicyObjectOrBuilder> 
      getAttributeGrantsOrBuilderList();
  /**
   * <code>repeated .policy.kasregistry.GrantedPolicyObject attribute_grants = 3 [json_name = "attributeGrants"];</code>
   */
  io.opentdf.platform.policy.kasregistry.GrantedPolicyObjectOrBuilder getAttributeGrantsOrBuilder(
      int index);

  /**
   * <code>repeated .policy.kasregistry.GrantedPolicyObject value_grants = 4 [json_name = "valueGrants"];</code>
   */
  java.util.List<io.opentdf.platform.policy.kasregistry.GrantedPolicyObject> 
      getValueGrantsList();
  /**
   * <code>repeated .policy.kasregistry.GrantedPolicyObject value_grants = 4 [json_name = "valueGrants"];</code>
   */
  io.opentdf.platform.policy.kasregistry.GrantedPolicyObject getValueGrants(int index);
  /**
   * <code>repeated .policy.kasregistry.GrantedPolicyObject value_grants = 4 [json_name = "valueGrants"];</code>
   */
  int getValueGrantsCount();
  /**
   * <code>repeated .policy.kasregistry.GrantedPolicyObject value_grants = 4 [json_name = "valueGrants"];</code>
   */
  java.util.List<? extends io.opentdf.platform.policy.kasregistry.GrantedPolicyObjectOrBuilder> 
      getValueGrantsOrBuilderList();
  /**
   * <code>repeated .policy.kasregistry.GrantedPolicyObject value_grants = 4 [json_name = "valueGrants"];</code>
   */
  io.opentdf.platform.policy.kasregistry.GrantedPolicyObjectOrBuilder getValueGrantsOrBuilder(
      int index);
}
