// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/kasregistry/key_access_server_registry.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.kasregistry;

public final class KeyAccessServerRegistryProto {
  private KeyAccessServerRegistryProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_kasregistry_GetKeyAccessServerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_kasregistry_GetKeyAccessServerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_kasregistry_GetKeyAccessServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_kasregistry_GetKeyAccessServerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_kasregistry_ListKeyAccessServersRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_kasregistry_ListKeyAccessServersRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_kasregistry_ListKeyAccessServersResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_kasregistry_ListKeyAccessServersResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_kasregistry_CreateKeyAccessServerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_kasregistry_CreateKeyAccessServerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_kasregistry_CreateKeyAccessServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_kasregistry_CreateKeyAccessServerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_kasregistry_UpdateKeyAccessServerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_kasregistry_UpdateKeyAccessServerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_kasregistry_UpdateKeyAccessServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_kasregistry_UpdateKeyAccessServerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_kasregistry_DeleteKeyAccessServerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_kasregistry_DeleteKeyAccessServerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_kasregistry_DeleteKeyAccessServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_kasregistry_DeleteKeyAccessServerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_kasregistry_GrantedPolicyObject_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_kasregistry_GrantedPolicyObject_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_kasregistry_KeyAccessServerGrants_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_kasregistry_KeyAccessServerGrants_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_kasregistry_ListKeyAccessServerGrantsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_kasregistry_ListKeyAccessServerGrantsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_kasregistry_ListKeyAccessServerGrantsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_kasregistry_ListKeyAccessServerGrantsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3policy/kasregistry/key_access_server_r" +
      "egistry.proto\022\022policy.kasregistry\032\033buf/v" +
      "alidate/validate.proto\032\023common/common.pr" +
      "oto\032\034google/api/annotations.proto\032\024polic" +
      "y/objects.proto\"3\n\031GetKeyAccessServerReq" +
      "uest\022\026\n\002id\030\001 \001(\tB\006\272H\003\310\001\001R\002id\"a\n\032GetKeyAc" +
      "cessServerResponse\022C\n\021key_access_server\030" +
      "\001 \001(\0132\027.policy.KeyAccessServerR\017keyAcces" +
      "sServer\"\035\n\033ListKeyAccessServersRequest\"e" +
      "\n\034ListKeyAccessServersResponse\022E\n\022key_ac" +
      "cess_servers\030\001 \003(\0132\027.policy.KeyAccessSer" +
      "verR\020keyAccessServers\"\247\001\n\034CreateKeyAcces" +
      "sServerRequest\022\030\n\003uri\030\001 \001(\tB\006\272H\003\310\001\001R\003uri" +
      "\0228\n\npublic_key\030\002 \001(\0132\021.policy.PublicKeyB" +
      "\006\272H\003\310\001\001R\tpublicKey\0223\n\010metadata\030d \001(\0132\027.c" +
      "ommon.MetadataMutableR\010metadata\"d\n\035Creat" +
      "eKeyAccessServerResponse\022C\n\021key_access_s" +
      "erver\030\001 \001(\0132\027.policy.KeyAccessServerR\017ke" +
      "yAccessServer\"\205\002\n\034UpdateKeyAccessServerR" +
      "equest\022\026\n\002id\030\001 \001(\tB\006\272H\003\310\001\001R\002id\022\020\n\003uri\030\002 " +
      "\001(\tR\003uri\0220\n\npublic_key\030\003 \001(\0132\021.policy.Pu" +
      "blicKeyR\tpublicKey\0223\n\010metadata\030d \001(\0132\027.c" +
      "ommon.MetadataMutableR\010metadata\022T\n\030metad" +
      "ata_update_behavior\030e \001(\0162\032.common.Metad" +
      "ataUpdateEnumR\026metadataUpdateBehavior\"d\n" +
      "\035UpdateKeyAccessServerResponse\022C\n\021key_ac" +
      "cess_server\030\001 \001(\0132\027.policy.KeyAccessServ" +
      "erR\017keyAccessServer\"6\n\034DeleteKeyAccessSe" +
      "rverRequest\022\026\n\002id\030\001 \001(\tB\006\272H\003\310\001\001R\002id\"d\n\035D" +
      "eleteKeyAccessServerResponse\022C\n\021key_acce" +
      "ss_server\030\001 \001(\0132\027.policy.KeyAccessServer" +
      "R\017keyAccessServer\"7\n\023GrantedPolicyObject" +
      "\022\016\n\002id\030\001 \001(\tR\002id\022\020\n\003fqn\030\002 \001(\tR\003fqn\"\320\002\n\025K" +
      "eyAccessServerGrants\022C\n\021key_access_serve" +
      "r\030\001 \001(\0132\027.policy.KeyAccessServerR\017keyAcc" +
      "essServer\022R\n\020namespace_grants\030\002 \003(\0132\'.po" +
      "licy.kasregistry.GrantedPolicyObjectR\017na" +
      "mespaceGrants\022R\n\020attribute_grants\030\003 \003(\0132" +
      "\'.policy.kasregistry.GrantedPolicyObject" +
      "R\017attributeGrants\022J\n\014value_grants\030\004 \003(\0132" +
      "\'.policy.kasregistry.GrantedPolicyObject" +
      "R\013valueGrants\"R\n ListKeyAccessServerGran" +
      "tsRequest\022\025\n\006kas_id\030\001 \001(\tR\005kasId\022\027\n\007kas_" +
      "uri\030\002 \001(\tR\006kasUri\"f\n!ListKeyAccessServer" +
      "GrantsResponse\022A\n\006grants\030\001 \003(\0132).policy." +
      "kasregistry.KeyAccessServerGrantsR\006grant" +
      "s2\344\007\n\036KeyAccessServerRegistryService\022\226\001\n" +
      "\024ListKeyAccessServers\022/.policy.kasregist" +
      "ry.ListKeyAccessServersRequest\0320.policy." +
      "kasregistry.ListKeyAccessServersResponse" +
      "\"\033\202\323\344\223\002\025\022\023/key-access-servers\022\225\001\n\022GetKey" +
      "AccessServer\022-.policy.kasregistry.GetKey" +
      "AccessServerRequest\032..policy.kasregistry" +
      ".GetKeyAccessServerResponse\" \202\323\344\223\002\032\022\030/ke" +
      "y-access-servers/{id}\022\234\001\n\025CreateKeyAcces" +
      "sServer\0220.policy.kasregistry.CreateKeyAc" +
      "cessServerRequest\0321.policy.kasregistry.C" +
      "reateKeyAccessServerResponse\"\036\202\323\344\223\002\030\"\023/k" +
      "ey-access-servers:\001*\022\241\001\n\025UpdateKeyAccess" +
      "Server\0220.policy.kasregistry.UpdateKeyAcc" +
      "essServerRequest\0321.policy.kasregistry.Up" +
      "dateKeyAccessServerResponse\"#\202\323\344\223\002\0352\030/ke" +
      "y-access-servers/{id}:\001*\022\236\001\n\025DeleteKeyAc" +
      "cessServer\0220.policy.kasregistry.DeleteKe" +
      "yAccessServerRequest\0321.policy.kasregistr" +
      "y.DeleteKeyAccessServerResponse\" \202\323\344\223\002\032*" +
      "\030/key-access-servers/{id}\022\254\001\n\031ListKeyAcc" +
      "essServerGrants\0224.policy.kasregistry.Lis" +
      "tKeyAccessServerGrantsRequest\0325.policy.k" +
      "asregistry.ListKeyAccessServerGrantsResp" +
      "onse\"\"\202\323\344\223\002\034\022\032/key-access-servers/grants" +
      "B\257\001\n&io.opentdf.platform.policy.kasregis" +
      "tryB\034KeyAccessServerRegistryProtoP\001\242\002\003PK" +
      "X\252\002\022Policy.Kasregistry\312\002\022Policy\\Kasregis" +
      "try\342\002\036Policy\\Kasregistry\\GPBMetadata\352\002\023P" +
      "olicy::Kasregistryb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
          io.opentdf.platform.common.CommonProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          io.opentdf.platform.policy.ObjectsProto.getDescriptor(),
        });
    internal_static_policy_kasregistry_GetKeyAccessServerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_policy_kasregistry_GetKeyAccessServerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_kasregistry_GetKeyAccessServerRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_policy_kasregistry_GetKeyAccessServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_policy_kasregistry_GetKeyAccessServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_kasregistry_GetKeyAccessServerResponse_descriptor,
        new java.lang.String[] { "KeyAccessServer", });
    internal_static_policy_kasregistry_ListKeyAccessServersRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_policy_kasregistry_ListKeyAccessServersRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_kasregistry_ListKeyAccessServersRequest_descriptor,
        new java.lang.String[] { });
    internal_static_policy_kasregistry_ListKeyAccessServersResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_policy_kasregistry_ListKeyAccessServersResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_kasregistry_ListKeyAccessServersResponse_descriptor,
        new java.lang.String[] { "KeyAccessServers", });
    internal_static_policy_kasregistry_CreateKeyAccessServerRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_policy_kasregistry_CreateKeyAccessServerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_kasregistry_CreateKeyAccessServerRequest_descriptor,
        new java.lang.String[] { "Uri", "PublicKey", "Metadata", });
    internal_static_policy_kasregistry_CreateKeyAccessServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_policy_kasregistry_CreateKeyAccessServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_kasregistry_CreateKeyAccessServerResponse_descriptor,
        new java.lang.String[] { "KeyAccessServer", });
    internal_static_policy_kasregistry_UpdateKeyAccessServerRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_policy_kasregistry_UpdateKeyAccessServerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_kasregistry_UpdateKeyAccessServerRequest_descriptor,
        new java.lang.String[] { "Id", "Uri", "PublicKey", "Metadata", "MetadataUpdateBehavior", });
    internal_static_policy_kasregistry_UpdateKeyAccessServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_policy_kasregistry_UpdateKeyAccessServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_kasregistry_UpdateKeyAccessServerResponse_descriptor,
        new java.lang.String[] { "KeyAccessServer", });
    internal_static_policy_kasregistry_DeleteKeyAccessServerRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_policy_kasregistry_DeleteKeyAccessServerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_kasregistry_DeleteKeyAccessServerRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_policy_kasregistry_DeleteKeyAccessServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_policy_kasregistry_DeleteKeyAccessServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_kasregistry_DeleteKeyAccessServerResponse_descriptor,
        new java.lang.String[] { "KeyAccessServer", });
    internal_static_policy_kasregistry_GrantedPolicyObject_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_policy_kasregistry_GrantedPolicyObject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_kasregistry_GrantedPolicyObject_descriptor,
        new java.lang.String[] { "Id", "Fqn", });
    internal_static_policy_kasregistry_KeyAccessServerGrants_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_policy_kasregistry_KeyAccessServerGrants_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_kasregistry_KeyAccessServerGrants_descriptor,
        new java.lang.String[] { "KeyAccessServer", "NamespaceGrants", "AttributeGrants", "ValueGrants", });
    internal_static_policy_kasregistry_ListKeyAccessServerGrantsRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_policy_kasregistry_ListKeyAccessServerGrantsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_kasregistry_ListKeyAccessServerGrantsRequest_descriptor,
        new java.lang.String[] { "KasId", "KasUri", });
    internal_static_policy_kasregistry_ListKeyAccessServerGrantsResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_policy_kasregistry_ListKeyAccessServerGrantsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_kasregistry_ListKeyAccessServerGrantsResponse_descriptor,
        new java.lang.String[] { "Grants", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    build.buf.validate.ValidateProto.getDescriptor();
    io.opentdf.platform.common.CommonProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    io.opentdf.platform.policy.ObjectsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
