// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/kasregistry/key_access_server_registry.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.kasregistry;

public interface ListKeyAccessServerGrantsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.kasregistry.ListKeyAccessServerGrantsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
   */
  java.util.List<io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants> 
      getGrantsList();
  /**
   * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
   */
  io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants getGrants(int index);
  /**
   * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
   */
  int getGrantsCount();
  /**
   * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
   */
  java.util.List<? extends io.opentdf.platform.policy.kasregistry.KeyAccessServerGrantsOrBuilder> 
      getGrantsOrBuilderList();
  /**
   * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
   */
  io.opentdf.platform.policy.kasregistry.KeyAccessServerGrantsOrBuilder getGrantsOrBuilder(
      int index);
}
