// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/kasregistry/key_access_server_registry.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.kasregistry;

/**
 * <pre>
 * LIST of KAS Grants returns flat response of grants to all policy objects. It does not
 * employ selectors for grants to specific policy objects or build the attribute tree relation.
 * If grants to a known namespace, attribute, or value are needed, use the respective
 * GET request to the specific policy object.
 * </pre>
 *
 * Protobuf type {@code policy.kasregistry.ListKeyAccessServerGrantsRequest}
 */
public final class ListKeyAccessServerGrantsRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:policy.kasregistry.ListKeyAccessServerGrantsRequest)
    ListKeyAccessServerGrantsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListKeyAccessServerGrantsRequest.newBuilder() to construct.
  private ListKeyAccessServerGrantsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListKeyAccessServerGrantsRequest() {
    kasId_ = "";
    kasUri_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListKeyAccessServerGrantsRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opentdf.platform.policy.kasregistry.KeyAccessServerRegistryProto.internal_static_policy_kasregistry_ListKeyAccessServerGrantsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opentdf.platform.policy.kasregistry.KeyAccessServerRegistryProto.internal_static_policy_kasregistry_ListKeyAccessServerGrantsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest.class, io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest.Builder.class);
  }

  public static final int KAS_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object kasId_ = "";
  /**
   * <pre>
   * Optional
   * Filter LIST by either ID or URI of a registered Key Access Server.
   * If neither is provided, grants from all registered KASs to policy attribute objects are returned.
   * </pre>
   *
   * <code>string kas_id = 1 [json_name = "kasId"];</code>
   * @return The kasId.
   */
  @java.lang.Override
  public java.lang.String getKasId() {
    java.lang.Object ref = kasId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      kasId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional
   * Filter LIST by either ID or URI of a registered Key Access Server.
   * If neither is provided, grants from all registered KASs to policy attribute objects are returned.
   * </pre>
   *
   * <code>string kas_id = 1 [json_name = "kasId"];</code>
   * @return The bytes for kasId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKasIdBytes() {
    java.lang.Object ref = kasId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      kasId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KAS_URI_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object kasUri_ = "";
  /**
   * <code>string kas_uri = 2 [json_name = "kasUri"];</code>
   * @return The kasUri.
   */
  @java.lang.Override
  public java.lang.String getKasUri() {
    java.lang.Object ref = kasUri_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      kasUri_ = s;
      return s;
    }
  }
  /**
   * <code>string kas_uri = 2 [json_name = "kasUri"];</code>
   * @return The bytes for kasUri.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKasUriBytes() {
    java.lang.Object ref = kasUri_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      kasUri_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(kasId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, kasId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(kasUri_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, kasUri_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(kasId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, kasId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(kasUri_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, kasUri_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest)) {
      return super.equals(obj);
    }
    io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest other = (io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest) obj;

    if (!getKasId()
        .equals(other.getKasId())) return false;
    if (!getKasUri()
        .equals(other.getKasUri())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KAS_ID_FIELD_NUMBER;
    hash = (53 * hash) + getKasId().hashCode();
    hash = (37 * hash) + KAS_URI_FIELD_NUMBER;
    hash = (53 * hash) + getKasUri().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * LIST of KAS Grants returns flat response of grants to all policy objects. It does not
   * employ selectors for grants to specific policy objects or build the attribute tree relation.
   * If grants to a known namespace, attribute, or value are needed, use the respective
   * GET request to the specific policy object.
   * </pre>
   *
   * Protobuf type {@code policy.kasregistry.ListKeyAccessServerGrantsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:policy.kasregistry.ListKeyAccessServerGrantsRequest)
      io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opentdf.platform.policy.kasregistry.KeyAccessServerRegistryProto.internal_static_policy_kasregistry_ListKeyAccessServerGrantsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opentdf.platform.policy.kasregistry.KeyAccessServerRegistryProto.internal_static_policy_kasregistry_ListKeyAccessServerGrantsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest.class, io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest.Builder.class);
    }

    // Construct using io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      kasId_ = "";
      kasUri_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opentdf.platform.policy.kasregistry.KeyAccessServerRegistryProto.internal_static_policy_kasregistry_ListKeyAccessServerGrantsRequest_descriptor;
    }

    @java.lang.Override
    public io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest getDefaultInstanceForType() {
      return io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest build() {
      io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest buildPartial() {
      io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest result = new io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.kasId_ = kasId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.kasUri_ = kasUri_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest) {
        return mergeFrom((io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest other) {
      if (other == io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest.getDefaultInstance()) return this;
      if (!other.getKasId().isEmpty()) {
        kasId_ = other.kasId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getKasUri().isEmpty()) {
        kasUri_ = other.kasUri_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              kasId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              kasUri_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object kasId_ = "";
    /**
     * <pre>
     * Optional
     * Filter LIST by either ID or URI of a registered Key Access Server.
     * If neither is provided, grants from all registered KASs to policy attribute objects are returned.
     * </pre>
     *
     * <code>string kas_id = 1 [json_name = "kasId"];</code>
     * @return The kasId.
     */
    public java.lang.String getKasId() {
      java.lang.Object ref = kasId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kasId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional
     * Filter LIST by either ID or URI of a registered Key Access Server.
     * If neither is provided, grants from all registered KASs to policy attribute objects are returned.
     * </pre>
     *
     * <code>string kas_id = 1 [json_name = "kasId"];</code>
     * @return The bytes for kasId.
     */
    public com.google.protobuf.ByteString
        getKasIdBytes() {
      java.lang.Object ref = kasId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kasId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional
     * Filter LIST by either ID or URI of a registered Key Access Server.
     * If neither is provided, grants from all registered KASs to policy attribute objects are returned.
     * </pre>
     *
     * <code>string kas_id = 1 [json_name = "kasId"];</code>
     * @param value The kasId to set.
     * @return This builder for chaining.
     */
    public Builder setKasId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      kasId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional
     * Filter LIST by either ID or URI of a registered Key Access Server.
     * If neither is provided, grants from all registered KASs to policy attribute objects are returned.
     * </pre>
     *
     * <code>string kas_id = 1 [json_name = "kasId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKasId() {
      kasId_ = getDefaultInstance().getKasId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional
     * Filter LIST by either ID or URI of a registered Key Access Server.
     * If neither is provided, grants from all registered KASs to policy attribute objects are returned.
     * </pre>
     *
     * <code>string kas_id = 1 [json_name = "kasId"];</code>
     * @param value The bytes for kasId to set.
     * @return This builder for chaining.
     */
    public Builder setKasIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      kasId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object kasUri_ = "";
    /**
     * <code>string kas_uri = 2 [json_name = "kasUri"];</code>
     * @return The kasUri.
     */
    public java.lang.String getKasUri() {
      java.lang.Object ref = kasUri_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        kasUri_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string kas_uri = 2 [json_name = "kasUri"];</code>
     * @return The bytes for kasUri.
     */
    public com.google.protobuf.ByteString
        getKasUriBytes() {
      java.lang.Object ref = kasUri_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kasUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string kas_uri = 2 [json_name = "kasUri"];</code>
     * @param value The kasUri to set.
     * @return This builder for chaining.
     */
    public Builder setKasUri(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      kasUri_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string kas_uri = 2 [json_name = "kasUri"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKasUri() {
      kasUri_ = getDefaultInstance().getKasUri();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string kas_uri = 2 [json_name = "kasUri"];</code>
     * @param value The bytes for kasUri to set.
     * @return This builder for chaining.
     */
    public Builder setKasUriBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      kasUri_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:policy.kasregistry.ListKeyAccessServerGrantsRequest)
  }

  // @@protoc_insertion_point(class_scope:policy.kasregistry.ListKeyAccessServerGrantsRequest)
  private static final io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest();
  }

  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListKeyAccessServerGrantsRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListKeyAccessServerGrantsRequest>() {
    @java.lang.Override
    public ListKeyAccessServerGrantsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListKeyAccessServerGrantsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListKeyAccessServerGrantsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

