// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/kasregistry/key_access_server_registry.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.kasregistry;

public interface ListKeyAccessServersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.kasregistry.ListKeyAccessServersRequest)
    com.google.protobuf.MessageOrBuilder {
}
