// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/kasregistry/key_access_server_registry.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.kasregistry;

/**
 * Protobuf type {@code policy.kasregistry.ListKeyAccessServerGrantsResponse}
 */
public final class ListKeyAccessServerGrantsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:policy.kasregistry.ListKeyAccessServerGrantsResponse)
    ListKeyAccessServerGrantsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListKeyAccessServerGrantsResponse.newBuilder() to construct.
  private ListKeyAccessServerGrantsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListKeyAccessServerGrantsResponse() {
    grants_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListKeyAccessServerGrantsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opentdf.platform.policy.kasregistry.KeyAccessServerRegistryProto.internal_static_policy_kasregistry_ListKeyAccessServerGrantsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opentdf.platform.policy.kasregistry.KeyAccessServerRegistryProto.internal_static_policy_kasregistry_ListKeyAccessServerGrantsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse.class, io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse.Builder.class);
  }

  public static final int GRANTS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants> grants_;
  /**
   * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
   */
  @java.lang.Override
  public java.util.List<io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants> getGrantsList() {
    return grants_;
  }
  /**
   * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.opentdf.platform.policy.kasregistry.KeyAccessServerGrantsOrBuilder> 
      getGrantsOrBuilderList() {
    return grants_;
  }
  /**
   * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
   */
  @java.lang.Override
  public int getGrantsCount() {
    return grants_.size();
  }
  /**
   * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
   */
  @java.lang.Override
  public io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants getGrants(int index) {
    return grants_.get(index);
  }
  /**
   * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
   */
  @java.lang.Override
  public io.opentdf.platform.policy.kasregistry.KeyAccessServerGrantsOrBuilder getGrantsOrBuilder(
      int index) {
    return grants_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < grants_.size(); i++) {
      output.writeMessage(1, grants_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < grants_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, grants_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse)) {
      return super.equals(obj);
    }
    io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse other = (io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse) obj;

    if (!getGrantsList()
        .equals(other.getGrantsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getGrantsCount() > 0) {
      hash = (37 * hash) + GRANTS_FIELD_NUMBER;
      hash = (53 * hash) + getGrantsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code policy.kasregistry.ListKeyAccessServerGrantsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:policy.kasregistry.ListKeyAccessServerGrantsResponse)
      io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opentdf.platform.policy.kasregistry.KeyAccessServerRegistryProto.internal_static_policy_kasregistry_ListKeyAccessServerGrantsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opentdf.platform.policy.kasregistry.KeyAccessServerRegistryProto.internal_static_policy_kasregistry_ListKeyAccessServerGrantsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse.class, io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse.Builder.class);
    }

    // Construct using io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (grantsBuilder_ == null) {
        grants_ = java.util.Collections.emptyList();
      } else {
        grants_ = null;
        grantsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opentdf.platform.policy.kasregistry.KeyAccessServerRegistryProto.internal_static_policy_kasregistry_ListKeyAccessServerGrantsResponse_descriptor;
    }

    @java.lang.Override
    public io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse getDefaultInstanceForType() {
      return io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse build() {
      io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse buildPartial() {
      io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse result = new io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse result) {
      if (grantsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          grants_ = java.util.Collections.unmodifiableList(grants_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.grants_ = grants_;
      } else {
        result.grants_ = grantsBuilder_.build();
      }
    }

    private void buildPartial0(io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse) {
        return mergeFrom((io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse other) {
      if (other == io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse.getDefaultInstance()) return this;
      if (grantsBuilder_ == null) {
        if (!other.grants_.isEmpty()) {
          if (grants_.isEmpty()) {
            grants_ = other.grants_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGrantsIsMutable();
            grants_.addAll(other.grants_);
          }
          onChanged();
        }
      } else {
        if (!other.grants_.isEmpty()) {
          if (grantsBuilder_.isEmpty()) {
            grantsBuilder_.dispose();
            grantsBuilder_ = null;
            grants_ = other.grants_;
            bitField0_ = (bitField0_ & ~0x00000001);
            grantsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getGrantsFieldBuilder() : null;
          } else {
            grantsBuilder_.addAllMessages(other.grants_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants m =
                  input.readMessage(
                      io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants.parser(),
                      extensionRegistry);
              if (grantsBuilder_ == null) {
                ensureGrantsIsMutable();
                grants_.add(m);
              } else {
                grantsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants> grants_ =
      java.util.Collections.emptyList();
    private void ensureGrantsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        grants_ = new java.util.ArrayList<io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants>(grants_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants, io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants.Builder, io.opentdf.platform.policy.kasregistry.KeyAccessServerGrantsOrBuilder> grantsBuilder_;

    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public java.util.List<io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants> getGrantsList() {
      if (grantsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(grants_);
      } else {
        return grantsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public int getGrantsCount() {
      if (grantsBuilder_ == null) {
        return grants_.size();
      } else {
        return grantsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants getGrants(int index) {
      if (grantsBuilder_ == null) {
        return grants_.get(index);
      } else {
        return grantsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public Builder setGrants(
        int index, io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants value) {
      if (grantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGrantsIsMutable();
        grants_.set(index, value);
        onChanged();
      } else {
        grantsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public Builder setGrants(
        int index, io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants.Builder builderForValue) {
      if (grantsBuilder_ == null) {
        ensureGrantsIsMutable();
        grants_.set(index, builderForValue.build());
        onChanged();
      } else {
        grantsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public Builder addGrants(io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants value) {
      if (grantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGrantsIsMutable();
        grants_.add(value);
        onChanged();
      } else {
        grantsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public Builder addGrants(
        int index, io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants value) {
      if (grantsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGrantsIsMutable();
        grants_.add(index, value);
        onChanged();
      } else {
        grantsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public Builder addGrants(
        io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants.Builder builderForValue) {
      if (grantsBuilder_ == null) {
        ensureGrantsIsMutable();
        grants_.add(builderForValue.build());
        onChanged();
      } else {
        grantsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public Builder addGrants(
        int index, io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants.Builder builderForValue) {
      if (grantsBuilder_ == null) {
        ensureGrantsIsMutable();
        grants_.add(index, builderForValue.build());
        onChanged();
      } else {
        grantsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public Builder addAllGrants(
        java.lang.Iterable<? extends io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants> values) {
      if (grantsBuilder_ == null) {
        ensureGrantsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, grants_);
        onChanged();
      } else {
        grantsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public Builder clearGrants() {
      if (grantsBuilder_ == null) {
        grants_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        grantsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public Builder removeGrants(int index) {
      if (grantsBuilder_ == null) {
        ensureGrantsIsMutable();
        grants_.remove(index);
        onChanged();
      } else {
        grantsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants.Builder getGrantsBuilder(
        int index) {
      return getGrantsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public io.opentdf.platform.policy.kasregistry.KeyAccessServerGrantsOrBuilder getGrantsOrBuilder(
        int index) {
      if (grantsBuilder_ == null) {
        return grants_.get(index);  } else {
        return grantsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public java.util.List<? extends io.opentdf.platform.policy.kasregistry.KeyAccessServerGrantsOrBuilder> 
         getGrantsOrBuilderList() {
      if (grantsBuilder_ != null) {
        return grantsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(grants_);
      }
    }
    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants.Builder addGrantsBuilder() {
      return getGrantsFieldBuilder().addBuilder(
          io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants.getDefaultInstance());
    }
    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants.Builder addGrantsBuilder(
        int index) {
      return getGrantsFieldBuilder().addBuilder(
          index, io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants.getDefaultInstance());
    }
    /**
     * <code>repeated .policy.kasregistry.KeyAccessServerGrants grants = 1 [json_name = "grants"];</code>
     */
    public java.util.List<io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants.Builder> 
         getGrantsBuilderList() {
      return getGrantsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants, io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants.Builder, io.opentdf.platform.policy.kasregistry.KeyAccessServerGrantsOrBuilder> 
        getGrantsFieldBuilder() {
      if (grantsBuilder_ == null) {
        grantsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants, io.opentdf.platform.policy.kasregistry.KeyAccessServerGrants.Builder, io.opentdf.platform.policy.kasregistry.KeyAccessServerGrantsOrBuilder>(
                grants_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        grants_ = null;
      }
      return grantsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:policy.kasregistry.ListKeyAccessServerGrantsResponse)
  }

  // @@protoc_insertion_point(class_scope:policy.kasregistry.ListKeyAccessServerGrantsResponse)
  private static final io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse();
  }

  public static io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListKeyAccessServerGrantsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListKeyAccessServerGrantsResponse>() {
    @java.lang.Override
    public ListKeyAccessServerGrantsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListKeyAccessServerGrantsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListKeyAccessServerGrantsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opentdf.platform.policy.kasregistry.ListKeyAccessServerGrantsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

