// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/namespaces/namespaces.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.namespaces;

public final class NamespacesProto {
  private NamespacesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_namespaces_NamespaceKeyAccessServer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_namespaces_NamespaceKeyAccessServer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_namespaces_GetNamespaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_namespaces_GetNamespaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_namespaces_GetNamespaceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_namespaces_GetNamespaceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_namespaces_ListNamespacesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_namespaces_ListNamespacesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_namespaces_ListNamespacesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_namespaces_ListNamespacesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_namespaces_CreateNamespaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_namespaces_CreateNamespaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_namespaces_CreateNamespaceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_namespaces_CreateNamespaceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_namespaces_UpdateNamespaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_namespaces_UpdateNamespaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_namespaces_UpdateNamespaceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_namespaces_UpdateNamespaceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_namespaces_DeactivateNamespaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_namespaces_DeactivateNamespaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_namespaces_DeactivateNamespaceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_namespaces_DeactivateNamespaceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_namespaces_AssignKeyAccessServerToNamespaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_namespaces_AssignKeyAccessServerToNamespaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_namespaces_AssignKeyAccessServerToNamespaceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_namespaces_AssignKeyAccessServerToNamespaceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_namespaces_RemoveKeyAccessServerFromNamespaceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_namespaces_RemoveKeyAccessServerFromNamespaceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_policy_namespaces_RemoveKeyAccessServerFromNamespaceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_policy_namespaces_RemoveKeyAccessServerFromNamespaceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"policy/namespaces/namespaces.proto\022\021po" +
      "licy.namespaces\032\033buf/validate/validate.p" +
      "roto\032\034google/api/annotations.proto\032\023comm" +
      "on/common.proto\032\024policy/objects.proto\"n\n" +
      "\030NamespaceKeyAccessServer\022!\n\014namespace_i" +
      "d\030\001 \001(\tR\013namespaceId\022/\n\024key_access_serve" +
      "r_id\030\002 \001(\tR\021keyAccessServerId\"-\n\023GetName" +
      "spaceRequest\022\026\n\002id\030\001 \001(\tB\006\272H\003\310\001\001R\002id\"G\n\024" +
      "GetNamespaceResponse\022/\n\tnamespace\030\001 \001(\0132" +
      "\021.policy.NamespaceR\tnamespace\"F\n\025ListNam" +
      "espacesRequest\022-\n\005state\030\001 \001(\0162\027.common.A" +
      "ctiveStateEnumR\005state\"K\n\026ListNamespacesR" +
      "esponse\0221\n\nnamespaces\030\001 \003(\0132\021.policy.Nam" +
      "espaceR\nnamespaces\"\376\004\n\026CreateNamespaceRe" +
      "quest\022\256\004\n\004name\030\001 \001(\tB\231\004\272H\225\004r\003\030\375\001\272\001\211\004\n\020na" +
      "mespace_format\022\241\003Namespace must be a val" +
      "id hostname. It should include at least " +
      "one dot, with each segment (label) start" +
      "ing and ending with an alphanumeric char" +
      "acter. Each label must be 1 to 63 charac" +
      "ters long, allowing hyphens but not as t" +
      "he first or last character. The top-leve" +
      "l domain (the last segment after the fin" +
      "al dot) must consist of at least two alp" +
      "habetic characters. The stored namespace" +
      " will be normalized to lower case.\032Qthis" +
      ".matches(\'^([a-zA-Z0-9]([a-zA-Z0-9\\\\-]{0" +
      ",61}[a-zA-Z0-9])?\\\\.)+[a-zA-Z]{2,}$\')\310\001\001" +
      "R\004name\0223\n\010metadata\030d \001(\0132\027.common.Metada" +
      "taMutableR\010metadata\"J\n\027CreateNamespaceRe" +
      "sponse\022/\n\tnamespace\030\001 \001(\0132\021.policy.Names" +
      "paceR\tnamespace\"\273\001\n\026UpdateNamespaceReque" +
      "st\022\026\n\002id\030\001 \001(\tB\006\272H\003\310\001\001R\002id\0223\n\010metadata\030d" +
      " \001(\0132\027.common.MetadataMutableR\010metadata\022" +
      "T\n\030metadata_update_behavior\030e \001(\0162\032.comm" +
      "on.MetadataUpdateEnumR\026metadataUpdateBeh" +
      "avior\"J\n\027UpdateNamespaceResponse\022/\n\tname" +
      "space\030\001 \001(\0132\021.policy.NamespaceR\tnamespac" +
      "e\"4\n\032DeactivateNamespaceRequest\022\026\n\002id\030\001 " +
      "\001(\tB\006\272H\003\310\001\001R\002id\"\035\n\033DeactivateNamespaceRe" +
      "sponse\"\225\001\n\'AssignKeyAccessServerToNamesp" +
      "aceRequest\022j\n\033namespace_key_access_serve" +
      "r\030\001 \001(\0132+.policy.namespaces.NamespaceKey" +
      "AccessServerR\030namespaceKeyAccessServer\"\226" +
      "\001\n(AssignKeyAccessServerToNamespaceRespo" +
      "nse\022j\n\033namespace_key_access_server\030\001 \001(\013" +
      "2+.policy.namespaces.NamespaceKeyAccessS" +
      "erverR\030namespaceKeyAccessServer\"\227\001\n)Remo" +
      "veKeyAccessServerFromNamespaceRequest\022j\n" +
      "\033namespace_key_access_server\030\001 \001(\0132+.pol" +
      "icy.namespaces.NamespaceKeyAccessServerR" +
      "\030namespaceKeyAccessServer\"\230\001\n*RemoveKeyA" +
      "ccessServerFromNamespaceResponse\022j\n\033name" +
      "space_key_access_server\030\001 \001(\0132+.policy.n" +
      "amespaces.NamespaceKeyAccessServerR\030name" +
      "spaceKeyAccessServer2\253\t\n\020NamespaceServic" +
      "e\022\204\001\n\014GetNamespace\022&.policy.namespaces.G" +
      "etNamespaceRequest\032\'.policy.namespaces.G" +
      "etNamespaceResponse\"#\202\323\344\223\002\035\022\033/attributes" +
      "/namespaces/{id}\022\205\001\n\016ListNamespaces\022(.po" +
      "licy.namespaces.ListNamespacesRequest\032)." +
      "policy.namespaces.ListNamespacesResponse" +
      "\"\036\202\323\344\223\002\030\022\026/attributes/namespaces\022\213\001\n\017Cre" +
      "ateNamespace\022).policy.namespaces.CreateN" +
      "amespaceRequest\032*.policy.namespaces.Crea" +
      "teNamespaceResponse\"!\202\323\344\223\002\033\"\026/attributes" +
      "/namespaces:\001*\022\220\001\n\017UpdateNamespace\022).pol" +
      "icy.namespaces.UpdateNamespaceRequest\032*." +
      "policy.namespaces.UpdateNamespaceRespons" +
      "e\"&\202\323\344\223\002 2\033/attributes/namespaces/{id}:\001" +
      "*\022\231\001\n\023DeactivateNamespace\022-.policy.names" +
      "paces.DeactivateNamespaceRequest\032..polic" +
      "y.namespaces.DeactivateNamespaceResponse" +
      "\"#\202\323\344\223\002\035*\033/attributes/namespaces/{id}\022\357\001" +
      "\n AssignKeyAccessServerToNamespace\022:.pol" +
      "icy.namespaces.AssignKeyAccessServerToNa" +
      "mespaceRequest\032;.policy.namespaces.Assig" +
      "nKeyAccessServerToNamespaceResponse\"R\202\323\344" +
      "\223\002L\"-/attributes/namespaces/keyaccessser" +
      "ver/grants:\033namespace_key_access_server\022" +
      "\330\001\n\"RemoveKeyAccessServerFromNamespace\022<" +
      ".policy.namespaces.RemoveKeyAccessServer" +
      "FromNamespaceRequest\032=.policy.namespaces" +
      ".RemoveKeyAccessServerFromNamespaceRespo" +
      "nse\"5\202\323\344\223\002/*-/attributes/namespaces/keya" +
      "ccessserver/grantsB\235\001\n%io.opentdf.platfo" +
      "rm.policy.namespacesB\017NamespacesProtoP\001\242" +
      "\002\003PNX\252\002\021Policy.Namespaces\312\002\021Policy\\Names" +
      "paces\342\002\035Policy\\Namespaces\\GPBMetadata\352\002\022" +
      "Policy::Namespacesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          build.buf.validate.ValidateProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
          io.opentdf.platform.common.CommonProto.getDescriptor(),
          io.opentdf.platform.policy.ObjectsProto.getDescriptor(),
        });
    internal_static_policy_namespaces_NamespaceKeyAccessServer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_policy_namespaces_NamespaceKeyAccessServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_namespaces_NamespaceKeyAccessServer_descriptor,
        new java.lang.String[] { "NamespaceId", "KeyAccessServerId", });
    internal_static_policy_namespaces_GetNamespaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_policy_namespaces_GetNamespaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_namespaces_GetNamespaceRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_policy_namespaces_GetNamespaceResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_policy_namespaces_GetNamespaceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_namespaces_GetNamespaceResponse_descriptor,
        new java.lang.String[] { "Namespace", });
    internal_static_policy_namespaces_ListNamespacesRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_policy_namespaces_ListNamespacesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_namespaces_ListNamespacesRequest_descriptor,
        new java.lang.String[] { "State", });
    internal_static_policy_namespaces_ListNamespacesResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_policy_namespaces_ListNamespacesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_namespaces_ListNamespacesResponse_descriptor,
        new java.lang.String[] { "Namespaces", });
    internal_static_policy_namespaces_CreateNamespaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_policy_namespaces_CreateNamespaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_namespaces_CreateNamespaceRequest_descriptor,
        new java.lang.String[] { "Name", "Metadata", });
    internal_static_policy_namespaces_CreateNamespaceResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_policy_namespaces_CreateNamespaceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_namespaces_CreateNamespaceResponse_descriptor,
        new java.lang.String[] { "Namespace", });
    internal_static_policy_namespaces_UpdateNamespaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_policy_namespaces_UpdateNamespaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_namespaces_UpdateNamespaceRequest_descriptor,
        new java.lang.String[] { "Id", "Metadata", "MetadataUpdateBehavior", });
    internal_static_policy_namespaces_UpdateNamespaceResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_policy_namespaces_UpdateNamespaceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_namespaces_UpdateNamespaceResponse_descriptor,
        new java.lang.String[] { "Namespace", });
    internal_static_policy_namespaces_DeactivateNamespaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_policy_namespaces_DeactivateNamespaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_namespaces_DeactivateNamespaceRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_policy_namespaces_DeactivateNamespaceResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_policy_namespaces_DeactivateNamespaceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_namespaces_DeactivateNamespaceResponse_descriptor,
        new java.lang.String[] { });
    internal_static_policy_namespaces_AssignKeyAccessServerToNamespaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_policy_namespaces_AssignKeyAccessServerToNamespaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_namespaces_AssignKeyAccessServerToNamespaceRequest_descriptor,
        new java.lang.String[] { "NamespaceKeyAccessServer", });
    internal_static_policy_namespaces_AssignKeyAccessServerToNamespaceResponse_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_policy_namespaces_AssignKeyAccessServerToNamespaceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_namespaces_AssignKeyAccessServerToNamespaceResponse_descriptor,
        new java.lang.String[] { "NamespaceKeyAccessServer", });
    internal_static_policy_namespaces_RemoveKeyAccessServerFromNamespaceRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_policy_namespaces_RemoveKeyAccessServerFromNamespaceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_namespaces_RemoveKeyAccessServerFromNamespaceRequest_descriptor,
        new java.lang.String[] { "NamespaceKeyAccessServer", });
    internal_static_policy_namespaces_RemoveKeyAccessServerFromNamespaceResponse_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_policy_namespaces_RemoveKeyAccessServerFromNamespaceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_policy_namespaces_RemoveKeyAccessServerFromNamespaceResponse_descriptor,
        new java.lang.String[] { "NamespaceKeyAccessServer", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(build.buf.validate.ValidateProto.field);
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    build.buf.validate.ValidateProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    io.opentdf.platform.common.CommonProto.getDescriptor();
    io.opentdf.platform.policy.ObjectsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
