// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/namespaces/namespaces.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.namespaces;

/**
 * Protobuf type {@code policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse}
 */
public final class RemoveKeyAccessServerFromNamespaceResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse)
    RemoveKeyAccessServerFromNamespaceResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RemoveKeyAccessServerFromNamespaceResponse.newBuilder() to construct.
  private RemoveKeyAccessServerFromNamespaceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RemoveKeyAccessServerFromNamespaceResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RemoveKeyAccessServerFromNamespaceResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.opentdf.platform.policy.namespaces.NamespacesProto.internal_static_policy_namespaces_RemoveKeyAccessServerFromNamespaceResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.opentdf.platform.policy.namespaces.NamespacesProto.internal_static_policy_namespaces_RemoveKeyAccessServerFromNamespaceResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse.class, io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse.Builder.class);
  }

  private int bitField0_;
  public static final int NAMESPACE_KEY_ACCESS_SERVER_FIELD_NUMBER = 1;
  private io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer namespaceKeyAccessServer_;
  /**
   * <code>.policy.namespaces.NamespaceKeyAccessServer namespace_key_access_server = 1 [json_name = "namespaceKeyAccessServer"];</code>
   * @return Whether the namespaceKeyAccessServer field is set.
   */
  @java.lang.Override
  public boolean hasNamespaceKeyAccessServer() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.policy.namespaces.NamespaceKeyAccessServer namespace_key_access_server = 1 [json_name = "namespaceKeyAccessServer"];</code>
   * @return The namespaceKeyAccessServer.
   */
  @java.lang.Override
  public io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer getNamespaceKeyAccessServer() {
    return namespaceKeyAccessServer_ == null ? io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer.getDefaultInstance() : namespaceKeyAccessServer_;
  }
  /**
   * <code>.policy.namespaces.NamespaceKeyAccessServer namespace_key_access_server = 1 [json_name = "namespaceKeyAccessServer"];</code>
   */
  @java.lang.Override
  public io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServerOrBuilder getNamespaceKeyAccessServerOrBuilder() {
    return namespaceKeyAccessServer_ == null ? io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer.getDefaultInstance() : namespaceKeyAccessServer_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getNamespaceKeyAccessServer());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getNamespaceKeyAccessServer());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse)) {
      return super.equals(obj);
    }
    io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse other = (io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse) obj;

    if (hasNamespaceKeyAccessServer() != other.hasNamespaceKeyAccessServer()) return false;
    if (hasNamespaceKeyAccessServer()) {
      if (!getNamespaceKeyAccessServer()
          .equals(other.getNamespaceKeyAccessServer())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasNamespaceKeyAccessServer()) {
      hash = (37 * hash) + NAMESPACE_KEY_ACCESS_SERVER_FIELD_NUMBER;
      hash = (53 * hash) + getNamespaceKeyAccessServer().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse)
      io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.opentdf.platform.policy.namespaces.NamespacesProto.internal_static_policy_namespaces_RemoveKeyAccessServerFromNamespaceResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.opentdf.platform.policy.namespaces.NamespacesProto.internal_static_policy_namespaces_RemoveKeyAccessServerFromNamespaceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse.class, io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse.Builder.class);
    }

    // Construct using io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNamespaceKeyAccessServerFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      namespaceKeyAccessServer_ = null;
      if (namespaceKeyAccessServerBuilder_ != null) {
        namespaceKeyAccessServerBuilder_.dispose();
        namespaceKeyAccessServerBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.opentdf.platform.policy.namespaces.NamespacesProto.internal_static_policy_namespaces_RemoveKeyAccessServerFromNamespaceResponse_descriptor;
    }

    @java.lang.Override
    public io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse getDefaultInstanceForType() {
      return io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse build() {
      io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse buildPartial() {
      io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse result = new io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.namespaceKeyAccessServer_ = namespaceKeyAccessServerBuilder_ == null
            ? namespaceKeyAccessServer_
            : namespaceKeyAccessServerBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse) {
        return mergeFrom((io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse other) {
      if (other == io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse.getDefaultInstance()) return this;
      if (other.hasNamespaceKeyAccessServer()) {
        mergeNamespaceKeyAccessServer(other.getNamespaceKeyAccessServer());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getNamespaceKeyAccessServerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer namespaceKeyAccessServer_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer, io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer.Builder, io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServerOrBuilder> namespaceKeyAccessServerBuilder_;
    /**
     * <code>.policy.namespaces.NamespaceKeyAccessServer namespace_key_access_server = 1 [json_name = "namespaceKeyAccessServer"];</code>
     * @return Whether the namespaceKeyAccessServer field is set.
     */
    public boolean hasNamespaceKeyAccessServer() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.policy.namespaces.NamespaceKeyAccessServer namespace_key_access_server = 1 [json_name = "namespaceKeyAccessServer"];</code>
     * @return The namespaceKeyAccessServer.
     */
    public io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer getNamespaceKeyAccessServer() {
      if (namespaceKeyAccessServerBuilder_ == null) {
        return namespaceKeyAccessServer_ == null ? io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer.getDefaultInstance() : namespaceKeyAccessServer_;
      } else {
        return namespaceKeyAccessServerBuilder_.getMessage();
      }
    }
    /**
     * <code>.policy.namespaces.NamespaceKeyAccessServer namespace_key_access_server = 1 [json_name = "namespaceKeyAccessServer"];</code>
     */
    public Builder setNamespaceKeyAccessServer(io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer value) {
      if (namespaceKeyAccessServerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        namespaceKeyAccessServer_ = value;
      } else {
        namespaceKeyAccessServerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.policy.namespaces.NamespaceKeyAccessServer namespace_key_access_server = 1 [json_name = "namespaceKeyAccessServer"];</code>
     */
    public Builder setNamespaceKeyAccessServer(
        io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer.Builder builderForValue) {
      if (namespaceKeyAccessServerBuilder_ == null) {
        namespaceKeyAccessServer_ = builderForValue.build();
      } else {
        namespaceKeyAccessServerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.policy.namespaces.NamespaceKeyAccessServer namespace_key_access_server = 1 [json_name = "namespaceKeyAccessServer"];</code>
     */
    public Builder mergeNamespaceKeyAccessServer(io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer value) {
      if (namespaceKeyAccessServerBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          namespaceKeyAccessServer_ != null &&
          namespaceKeyAccessServer_ != io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer.getDefaultInstance()) {
          getNamespaceKeyAccessServerBuilder().mergeFrom(value);
        } else {
          namespaceKeyAccessServer_ = value;
        }
      } else {
        namespaceKeyAccessServerBuilder_.mergeFrom(value);
      }
      if (namespaceKeyAccessServer_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.policy.namespaces.NamespaceKeyAccessServer namespace_key_access_server = 1 [json_name = "namespaceKeyAccessServer"];</code>
     */
    public Builder clearNamespaceKeyAccessServer() {
      bitField0_ = (bitField0_ & ~0x00000001);
      namespaceKeyAccessServer_ = null;
      if (namespaceKeyAccessServerBuilder_ != null) {
        namespaceKeyAccessServerBuilder_.dispose();
        namespaceKeyAccessServerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.policy.namespaces.NamespaceKeyAccessServer namespace_key_access_server = 1 [json_name = "namespaceKeyAccessServer"];</code>
     */
    public io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer.Builder getNamespaceKeyAccessServerBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getNamespaceKeyAccessServerFieldBuilder().getBuilder();
    }
    /**
     * <code>.policy.namespaces.NamespaceKeyAccessServer namespace_key_access_server = 1 [json_name = "namespaceKeyAccessServer"];</code>
     */
    public io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServerOrBuilder getNamespaceKeyAccessServerOrBuilder() {
      if (namespaceKeyAccessServerBuilder_ != null) {
        return namespaceKeyAccessServerBuilder_.getMessageOrBuilder();
      } else {
        return namespaceKeyAccessServer_ == null ?
            io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer.getDefaultInstance() : namespaceKeyAccessServer_;
      }
    }
    /**
     * <code>.policy.namespaces.NamespaceKeyAccessServer namespace_key_access_server = 1 [json_name = "namespaceKeyAccessServer"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer, io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer.Builder, io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServerOrBuilder> 
        getNamespaceKeyAccessServerFieldBuilder() {
      if (namespaceKeyAccessServerBuilder_ == null) {
        namespaceKeyAccessServerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer, io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer.Builder, io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServerOrBuilder>(
                getNamespaceKeyAccessServer(),
                getParentForChildren(),
                isClean());
        namespaceKeyAccessServer_ = null;
      }
      return namespaceKeyAccessServerBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse)
  }

  // @@protoc_insertion_point(class_scope:policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse)
  private static final io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse();
  }

  public static io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RemoveKeyAccessServerFromNamespaceResponse>
      PARSER = new com.google.protobuf.AbstractParser<RemoveKeyAccessServerFromNamespaceResponse>() {
    @java.lang.Override
    public RemoveKeyAccessServerFromNamespaceResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RemoveKeyAccessServerFromNamespaceResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RemoveKeyAccessServerFromNamespaceResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.opentdf.platform.policy.namespaces.RemoveKeyAccessServerFromNamespaceResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

