// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: policy/namespaces/namespaces.proto

// Protobuf Java Version: 3.25.3
package io.opentdf.platform.policy.namespaces;

public interface RemoveKeyAccessServerFromNamespaceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:policy.namespaces.RemoveKeyAccessServerFromNamespaceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.policy.namespaces.NamespaceKeyAccessServer namespace_key_access_server = 1 [json_name = "namespaceKeyAccessServer"];</code>
   * @return Whether the namespaceKeyAccessServer field is set.
   */
  boolean hasNamespaceKeyAccessServer();
  /**
   * <code>.policy.namespaces.NamespaceKeyAccessServer namespace_key_access_server = 1 [json_name = "namespaceKeyAccessServer"];</code>
   * @return The namespaceKeyAccessServer.
   */
  io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServer getNamespaceKeyAccessServer();
  /**
   * <code>.policy.namespaces.NamespaceKeyAccessServer namespace_key_access_server = 1 [json_name = "namespaceKeyAccessServer"];</code>
   */
  io.opentdf.platform.policy.namespaces.NamespaceKeyAccessServerOrBuilder getNamespaceKeyAccessServerOrBuilder();
}
