name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@f2acddfb5195534d487896a656232b016a682f3c # v1.9.0
        with:
          app-id: "${{ secrets.APP_ID }}"
          private-key: "${{ secrets.AUTOMATION_KEY }}"
      - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f
        id: release-please
        with:
          token: "${{ steps.generate_token.outputs.token }}"
          config-file: release-please.json
          manifest-file: .release-please-manifest.json
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Buf
        uses: bufbuild/buf-setup-action@aceb106d2419c4cff48863df90161d92decb8591
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK
        uses: actions/setup-java@5896cecc08fd8a1fbdfaf517e29b571164b031f7
        with:
          java-version: "11"
          distribution: "adopt"
          server-id: github
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUF_INPUT_HTTPS_USERNAME: opentdf-bot
          BUF_INPUT_HTTPS_PASSWORD: ${{ secrets.PERSONAL_ACCESS_TOKEN_OPENTDF }}
